### ISSUE TITLE
Story page fixes

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#128]
- [x] Give some context about what they're looking it? 
- [x] remove email from story in favour of username
- [x] if username is "other" don't display text here. Has been requested by "a other" is really weird
- [x] Story widget has broken image link. 
- [x] Long links can break the box : https://openaccessbutton.org/story/zNkLuvdXuMwjCbtw4. Can we display the paper title instead?
- [x] Are the actual stories showing up here? As in what they typed in?

**Comment by markmacgillivray** [comment]
What do you want the context to say? If they have come to the story from the action page, it makes sense. If there is a request, it links to it. But if not, then what?

Email gets displayed when there is no username, as per other issue about this problem. Let me know if you want me to display nothing instead of email if no username present.

Points 3 and 4 I can fix.

Links are only shown if there is no title. So yes long links will flow badly, but can't be helped. Something has to be shown, so I think if no title it just has to be the URL.

Yes, if the user provided a story, they should be. I can check.

**Comment by markmacgillivray** [comment]
@JosephMcArthur pinging you re the above

**Comment by markmacgillivray** [comment]
3 and 4 done, still need answers for others, so reassigning

**Comment by JosephMcArthur** [comment]
Fwiw, I think the context probably need to be more than I can think about now. So ignoring for now.

**Comment by JosephMcArthur** [comment]
If we don't have an email say "a user"

**Comment by markmacgillivray** [comment]
Done, to go live this afternoon
