### ISSUE TITLE
opendatabutton stories display user email, not username

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#132]
e.g https://opendatabutton.org/story/smGoSHjWYNRR2BwWq

**Comment by markmacgillivray** [comment]
This is because these users have not yet chosen a username for themselves, I think. So we have to display something. The signup docs do say we will display email address if no username is present. So we could just close this, or I could change it not to show anything if no username present. Let me know.

**Comment by markmacgillivray** [comment]
@JosephMcArthur just pinging you re. my previous comment

**Comment by markmacgillivray** [comment]
Nothing further can be done here either until choice about what you'd like displayed, so reassigning to @JosephMcArthur

**Comment by JosephMcArthur** [comment]
If no email display "a user"

**Comment by markmacgillivray** [comment]
Changed, to deploy this afternoon.
