### ISSUE TITLE
Fix story & request search

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#135]

**Comment by markmacgillivray** [comment]
For now the search functionality is just being used to provide the status filtering on the left hand column, so actually the search box on the top is not necessary. Later, a more interactive UI into requests as a whole may be better as a separate page. For the request and story pages at present, I have hidden the misleading search boxes and left the status filter choices on the request pages. There are no filters on the story pages yet. The functionality is there though, to add full text searching of any metadata that we have, and to add filters on other values such as email addresses, titles etc. For now it is not hugely useful because for example our requests are all to different email addresses, so filtering by email are all just unique records anyway.
