### ISSUE TITLE
ODB Request Changes

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#154]
- [x] Send name needs to change to Open Data Button on all emails
- [x] Links for holding the request are just raw, they need to be in buttons
- [x] Link to data from request page is to file on our server, I think, needs to be from OSF
- [x] You should need to be logged in to validate content (couldn't see if this was the case)
- [x] On hold should be "This content is expected in x days" on request pages and generally on copy. 
- [x] Insert username / story into the email

**Comment by markmacgillivray** [comment]
@JosephMcArthur need some more info on this: 

* what send name do you mean? what do you want it changed to?

* where you say "on hold should be more" - where do you mean? Where do you want it to say how long it is on hold for? Do you mean on the request page where the status shows as on hold? The problem with showing any counter here is that the author can put it on hold again, so the info would appear incorrect if someone went back to look, because the author may subsequently put it on hold again. So just saying "on hold" minimises inaccuracy by being sparse in the first place. There is no way round this unless we stop allowing authors to put things on hold more than once.

For link to date from request page, I assume you mean from the response page? Our successful requests say success and link to our response page, which did list buttons to download from our server, followed by URLs to get the files from the OSF instead. I have changed this though, so when I update the live system it will ONLY show buttons and they will go to the OSF pages if OSF links are available; if OSF links are not available, it will just show buttons to download from our server.

The links for holding the request page, I assume you mean you want buttons in the email - this is possible, but as it is not in html yet it may take a while to do so not sure I can get it done for tomorrow. Other points above can be done though, if you let me know answers to above.

**Comment by JosephMcArthur** [comment]
Have edited the description above to be clearer answering bullet one. For bullet two, this is a fair point. "on hold" isn't clear language though, could we say "expected soon"?  

OSF file fix sounds good. Thanks. 

For the links in emails, if you have to encode the buttons in HTML this issue will be helpful: https://github.com/RightToResearch/OpenCon-Website/issues/71 . In my last comment I have decent code examples for this.

**Comment by markmacgillivray** [comment]
Some of this remains relevant on new site dev, so moving onto next milestone

**Comment by JosephMcArthur** [comment]
Okay, this issue needs a bit of an update. 

- [ ] Send name needs to be "Open Access Button"
- [ ] Should come from requests@openaccessbutton.org. FYI: This address is registered to one of our google apps accounts, incase this matters.

**Comment by markmacgillivray** [comment]
The address currently used for mails from openaccessbutton is admin@openaccessbutton.org - do you want that changed so the email is always requests@openaccessbutton.org? Or do you want admin to remain the default one? For using this particular requests address just for certain emails, it will be possible to set that via the templates, so just checking if you want the default changed.

**Comment by markmacgillivray** [comment]
Should username/story be inserted in the email? If we do that it is less obvious that there is a public page where other people are seeing things, and where others can be adding support. I think having the email link to the page, and prodding the author to go there, gives a better sense of the public nature of the request, so they may be more likely to consider action, rather than just thinking it is something that can be ignored.

**Comment by markmacgillivray** [comment]
For changing the email templates to be html, putting in buttons and other layout features etc, I doubt I will have time for. Is anyone else going to do this before launch, or do we just go with flat text emails for now? I will be getting back to you later today with info on the email templating.

**Comment by JosephMcArthur** [comment]
For requests only, sending via requests@openaccessbutton.org would be ideal.

**Comment by JosephMcArthur** [comment]
> For changing the email templates to be html, putting in buttons and other layout features etc, I doubt I will have time for. Is anyone else going to do this before launch, or do we just go with flat text emails for now? I will be getting back to you later today with info on the email templating.

Just do what you can to get them in, and we can make them pretty later.

**Comment by JosephMcArthur** [comment]
> Should username/story be inserted in the email? If we do that it is less obvious that there is a public page where other people are seeing things, and where others can be adding support. I think having the email link to the page, and prodding the author to go there, gives a better sense of the public nature of the request, so they may be more likely to consider action, rather than just thinking it is something that can be ignored.

I think, to be honest, we have to do both. I think its important that the emails have a personal touch immediately, especially since this isn't clear "at a glance" from request pages right now.

**Comment by markmacgillivray** [comment]
Unassigning myself from copy issues - I should not be involved in these decisions at present, so tracking technical ones that I can make progress on.

**Comment by JosephMcArthur** [comment]
Mark can you make variables for

- [ ] user full name
- [ ] user affiliation
- [ ] user type (student etc)

please? 

Also, this should not block release of the site.

**Comment by markmacgillivray** [comment]
OK I have updated the emails/example.txt to list what user variables the system could provide. I will use that email example as the place to list variables that can be used, so when you request some in an issue they will be added there if they can be done.

**Comment by JosephMcArthur** [comment]
Thank you! I've slotted these into my placeholders however the email won't yet work in all contexts.

**Comment by markmacgillivray** [comment]
If you use a variable that does not exist, I can make it so that the email
still sends, so just try writing any email content to roughly make sense
even if a variable was missing. Or with earlier emails to a user account
that may not have say a username or fullname, just don't use them on those
emails, and just use them for later messages where we can more likely
expect those variables to exist (e.g. after the user has fully signed up
and given us their extra info)

**Comment by JosephMcArthur** [comment]
@markmacgillivray i've changed contact@openaccessbutton.org to requests@openaccessbutton.org. The latter is linked to our gapps account & contact@openaccessbutton.org gives a failure when you email it.

**Comment by chealsye** [comment]
@JosephMcArthur I don't quite understand what you need from me here.

**Comment by JosephMcArthur** [comment]
Okay, I've taken a look at this & have changed my mind a bit. 

* No buttons, this email is also ready quite programmatic & I think having buttons make it seems even more so. Tasteful links list fine. I have started this process and html-ified the email. 
* We need to split at least the original email for data & articles. The systems & information needed are too different.

**Comment by JosephMcArthur** [comment]
Okay, now:

* both versions contain the info needed, I think, in html.
* there are some missing links where I need to put those in, but I've tried to signify where links would be good
* I've tried to write copy that walks a fine line between generic & specific. However, I do use {{fullname}} which not all users will have (even if they've fully signed up previously). @markmacgillivray please advise on handling this. We can catch this in moderation and send the message manually for now. 
* using {{profession}} will occationally result in "other" or "prefer not to say" being put in. @markmacgillivray please advise on handling this. We can catch this in moderation and send the message manually for now. 

So, @chealsye, over to you on really honing this. All I've tried to do is provide an outline of what a HTML email could look like. 

One issue I did realise while html-ifying this is that if their inbox requests plain text this won't work very well. However, I think this a relatively few people though & they're probably used to reading awful email text. The added readability for most people will offset any downside here I think.

**Comment by markmacgillivray** [comment]
It is possible to deliver text and html in an email so that users who refuse html see a perfectly good text version. I actually prefer text versions when they are available. if you want to do this, it would be relatively simple to ensure the email system can send both types at the same time, and would be better to do now than later. But it does mean you would have to write and maintain .txt and .html versions of both.

Also, looking at the html one you made for author_request_data.html apart from the links, none of the rest of that html would actually be necessary - it is just paragraph tags, which plaintext would render the same as. The html <a> link wraps around the number will actually mean that the link to press for say a 7 day hold will be very small compared to how it was - someone would have to notice that the 7 itself is a link, and be willing to click it. Whereas with inserting the full web link in the email, the area to click on (for modern mail clients that make links clickable anyway even in text) is much larger and easier to notice, and means the user can copy and paste if they prefer (or if their mail client does not linkify it) although it does need explaining, e.g "for a seven day hold, click or paste this link:".

However it makes no technical difference to me - just options for keeping mail templates simpler, to ensure all possibilities are considered. I don't know what you don't know, so in the interest of progress and finding the best solution, it seems preferable to me to share as much information as possible to enable better decision making.

**Comment by markmacgillivray** [comment]
I do agree though that even in the html just using the links is better than putting buttons in - I think the buttons end up looking a bit tacky.

Re. the author_request_data.html one again though, and what to do about lacking a fullname etc, if you really want to word it like this where the fullname is required, the only option is that I can provide either fullname or username if they exist (which they will for new users but may not for old users), or even just their email address if you want that. But for {{profession}} there is no way round it - if you want to use that and the person chooses an option that does not work well in the context you write it into, it just will not work well.

If you are going to keep the emails split depending on type, it is a little harder for me to code that into the system because it will have to know which email to choose based on the type of the request - what you have done with this one, e.g. adding _data to the end of the name, would allow the system to pick out this template, BUT this is fragile and will only work if you consistently name templates like this. What about cases where you want a template that is suitable for both? Or will you now always want two templates for each sort of type? These are all possible, but are functionalities beyond what has already been discussed, and we are already at the last minute here.

(And as an aside, if templates are going to be specific to request type, then you won't need to use the {{type}} variable in the content at all - you can just write the word "data" in there.)

Also, I am not sure what you mean about fixing and sending manually - isn't the idea that these emails are going to be triggered automatically when the status changes? Or are you wanting to manually look at the request page and send that email yourself? If so, that is beyond discussed scope - we can do one or the other, but to be able to send an email that should then mean the system should not send the standard automatic one is functionality we just don't have yet.

**Comment by markmacgillivray** [comment]
The above are some of the reasons I made the author_request example more generic - the only really specific information about data in there is the OSF stuff, and actually the author does not need to know about that in the email - in the email we are asking them to do something, to go to a link where they will learn more (the request) and to go somewhere else to give us content. That means we have to locations at which we can provide more information to the author, such as saying that for a request it will be stored in OSF, and for an article it will go to Zenodo. This would keep the emails much simpler, easier to maintain the content of them, and for the time being at least would fit with the functionality we have. Although it is technically possible, I find that simpler solutions that put the complexity where it is better suited are usually better, both technically and non-technically.

**Comment by JosephMcArthur** [comment]
**so many things to respond to & consider**

> It is possible to deliver text and html in an email so that users who refuse html see a perfectly good text version. I actually prefer text versions when they are available. if you want to do this, it would be relatively simple to ensure the email system can send both types at the same time, and would be better to do now than later. But it does mean you would have to write and maintain .txt and .html versions of both.

It seems we agree that html links are better, but plain text is needed. I hope writing the extra .txt should be okay. Lets get this in if it's easy. 

> Also, I am not sure what you mean about fixing and sending manually - isn't the idea that these emails are going to be triggered automatically when the status changes? Or are you wanting to manually look at the request page and send that email yourself? If so, that is beyond discussed scope - we can do one or the other, but to be able to send an email that should then mean the system should not send the standard automatic one is functionality we just don't have yet.

On the public site's admin we could edit the text of the email before it sent, that's what I was referring too mainly here. Will that not be possible this time? 

> Re. the author_request_data.html one again though, and what to do about lacking a fullname etc, if you really want to word it like this where the fullname is required, the only option is that I can provide either fullname or username if they exist (which they will for new users but may not for old users), or even just their email address if you want that. But for {{profession}} there is no way round it - if you want to use that and the person chooses an option that does not work well in the context you write it into, it just will not work well.

Okay, if {{fullname}} can fall back to {{username}} that would be helpful. However, everyone should have {{profession}} from previous sign ups. Affiliation is the thing we have to worry about. However, we can leave that out for now & change later when we have a way of handling this. 

> The above are some of the reasons I made the author_request example more generic - the only really specific information about data in there is the OSF stuff, and actually the author does not need to know about that in the email - in the email we are asking them to do something, to go to a link where they will learn more (the request) and to go somewhere else to give us content. That means we have to locations at which we can provide more information to the author, such as saying that for a request it will be stored in OSF, and for an article it will go to Zenodo. This would keep the emails much simpler, easier to maintain the content of them, and for the time being at least would fit with the functionality we have. Although it is technically possible, I find that simpler solutions that put the complexity where it is better suited are usually better, both technically and non-technically.

Okay, I find the idea of moving complexity out of these emails & onto a webpage far more appealing. What we can say about OSF / Zenodo in an email isn't enough anyway, a webpage would need to say something regardless. I didn't consider this when splitting it but saw the OSF stuff as a blocker so split the messages. As an exploration of this route I've started a version that tries to remove that info. It's here: https://github.com/OAButton/oab_static/blob/develop/emails/author_request_simple.html. It's by no means perfect, but I also think it shows this can be done. 

> If you are going to keep the emails split depending on type, it is a little harder for me to code that into the system because it will have to know which email to choose based on the type of the request - what you have done with this one, e.g. adding _data to the end of the name, would allow the system to pick out this template, BUT this is fragile and will only work if you consistently name templates like this. What about cases where you want a template that is suitable for both? Or will you now always want two templates for each sort of type? These are all possible, but are functionalities beyond what has already been discussed, and we are already at the last minute here.

Long term, I think we will want to optimise & hone these - which I expect will mean splitting, but, for now lets try and be strict and keep it simple. 

If I've missed anything above - please say.

**Comment by JosephMcArthur** [comment]
> Also, looking at the html one you made for author_request_data.html apart from the links, none of the rest of that html would actually be necessary - it is just paragraph tags, which plaintext would render the same as. The html link wraps around the number will actually mean that the link to press for say a 7 day hold will be very small compared to how it was - someone would have to notice that the 7 itself is a link, and be willing to click it. Whereas with inserting the full web link in the email, the area to click on (for modern mail clients that make links clickable anyway even in text) is much larger and easier to notice, and means the user can copy and paste if they prefer (or if their mail client does not linkify it) although it does need explaining, e.g "for a seven day hold, click or paste this link:".

I think I've got a fairly nice away around this now, which is also inclusive of articles & data.

**Comment by markmacgillivray** [comment]
Via admin it is possible to load up an email template and edit it then send it. (this will be testable soon), and the idea was also that certain email templates would be triggered when status changes or other events occur. But that does not mean that there is any functionality to STOP an email being sent when a particular event occurs just because a particular email was already sent from admin.

The public (old, live) site has the ability to edit an email and send, yes, but it has no ability to send them automatically - the idea then was that the emails and status changes would be done manually for the requests we received (a common practice with new tech services - fake the automation), although it never was.

Having one or the other is possible, having both is also possible but requires further development that we have not as yet identified as a requirement.

**Comment by JosephMcArthur** [comment]
Okay, go manual.

**Comment by markmacgillivray** [comment]
OK will prioritise manual emailing

**Comment by JosephMcArthur** [comment]
To be clear. This means that:
* we'll moderate each email when a request is submitted
* we'll follow up with authors manually (it won't go automatically)

and links like hold / received / refused won't generate emails - they'll go to the request page and a confirmation message (or next action) will be seen there

**Comment by markmacgillivray** [comment]
Yes, it was/is

* new request gets status help if necessary info missing
* new request or helped request automatically goes to status moderate
* someone has to manually move from moderate to progress
* progress triggers an email to the author (but now it won't, someone will send one manually before they change the status)
* author clicks a hold or refuse link, status automatically changes to hold or refused
* (changing to hold or refused would have triggered an auto email but now won't)
* (whilst on hold, followup emails would be triggered each week but now won't)
* if an author submits something to us, status auto changes to received
* (this would have notified the author, the creator, and the supporters, but now won't)

We can come back at a later time to deciding when to turn automation on.

**Comment by markmacgillivray** [comment]
By was/is I mean the auto-email process that was intended, that is being written into the email template system functionality now, for the new system, would have been as above, but now whilst we keep automatic emailing turned off the stuff in brackets won't happen.

Some of the email automation was already in place in the old system, but it did not use templates, so the emails could not easily be edited by content creators - which is why now moving to a template system for emails. However none of the old email automations ever took place anyway, because no requests were moved into progress.

The intended automation described above can still be finished in the new code, and can still be turned on at some future date. But to do that we either have to be happy that it will not be necessary to manually send the emails that the system will automatically send, or we need a more complex management system that tracks which emails have been sent to which users, about which requests, and at what time, so that the system can then check whether or not to send automated emails when they are triggered. This is the more complex functionality that we have not yet considered, and do not yet have.

**Comment by JosephMcArthur** [comment]
> new request gets status help if necessary info missing

Should we have an email to requestors / supporters for this? 

> new request or helped request automatically goes to status moderate
> someone has to manually move from moderate to progress

Email for this discussed above. Copy for an email to users telling them their request is in progress is in. 

> progress triggers an email to the author (but now it won't, someone will send one manually before they change the status)
> author clicks a hold or refuse link, status automatically changes to hold or refused
> (changing to hold or refused would have triggered an auto email but now won't)

No email needed for authors. Email for requestors in /emails.

> (whilst on hold, followup emails would be triggered each week but now won't)

while manual this is too hard, no copy written. 

> if an author submits something to us, status auto changes to received
> (this would have notified the author, the creator, and the supporters, but now won't)

email for this created.

**Comment by markmacgillivray** [comment]
Yeah sorry I missed the one where if the new request needs help then we should email the request creator. But we cannot email supporters, there won't be any.

**Comment by JosephMcArthur** [comment]
Made one!

**Comment by JosephMcArthur** [comment]
All of these templates can now be tested from /admin. The emails needs to be test & refined, however this issue could be closed and that taken care of in specific issues.

**Comment by JosephMcArthur** [comment]
Closing this now. Issues with emails can be dealt with individually.

**Comment by markmacgillivray** [comment]
Yes, it was/is

* new request gets status help if necessary info missing
* new request or helped request automatically goes to status moderate
* someone has to manually move from moderate to progress
* progress triggers an email to the author (but now it won't, someone will
send one manually before they change the status)
* author clicks a hold or refuse link, status automatically changes to hold
or refused
* (changing to hold or refused would have triggered an auto email but now
won't)
* (whilst on hold, followup emails would be triggered each week but now
won't)
* if an author submits something to us, status auto changes to received
* (this would have notified the author, the creator, and the supporters,
but now won't)

We can come back at a later time to deciding when to turn automation on.

**Comment by markmacgillivray** [comment]
It is possible to deliver text and html in an email so that users who
refuse html see a perfectly good text version. I actually prefer text
versions when they are available. if you want to do this, it would be
relatively simple to ensure the email system can send both types at the
same time, and would be better to do now than later. But it does mean you
would have to write and maintain .txt and .html versions of both.

Also, looking at the html one you made for author_request_data.html apart
from the links, none of the rest of that html would actually be necessary -
it is just paragraph tags, which plaintext would render the same as. The
html <a> link wraps around the number will actually mean that the link to
press for say a 7 day hold will be very small compared to how it was -
someone would have to notice that the 7 itself is a link, and be willing to
click it. Whereas with inserting the full web link in the email, the area
to click on (for modern mail clients that make links clickable anyway even
in text) is much larger and easier to notice, and means the user can copy
and paste if they prefer (or if their mail client does not linkify it)
although it does need explaining, e.g "for a seven day hold, click or paste
this link:".

However it makes no technical difference to me - just options for keeping
mail templates simpler, to ensure all possibilities are considered. I don't
know what you don't know, so in the interest of progress and finding the
best solution, it seems preferable to me to share as much information as
possible to enable better decision making.
