### ISSUE TITLE
Graphics to support text explanations

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/backend#182]
For example as a first attempt, the getting started instructions is about nine lines long. It would be good if we had a set of graphics that could go next to each of the actions (or related sets of actions). There is likely to be more of this work on an ongoing basis - any time we make site content it should be presented in a nice mix of text and graphical instructions, and we should have a person who can do that when given a set of text - produce a graphical walkthrough to support the instructions. Firstly we need a style to be used across such graphics though. The little hand / fists on the front of the openaccessbutton site could be a starting point for this.

**Comment by markmacgillivray** [comment]
front page of new dev at oab.test.cottagelabs.com now just uses the oabutton logo itself. That is probably fine for there. But the getting started could do with some. Also on login a symbol to sign up ./ login would be good. Plus on requests, whether exploring or creating, would be good if we have some symbol for a request. There are also some statuses of requests, which it may be nice to visualise, but don't actually know what they are yet. Perhaps a generic set though like new,moderating,progress,waiting,success or something like that (not in words of course, just those concepts).

Also on the plugin itself, would be good to have symbols for data and article, and eventually others. these could do with being representable as available,requested,unavailable.

For useful graphics, png files are fine, and some could actually just be transparent then I could background colourise them where necessary. So don't actually need to be too "graphical". e.g. a request could have a symbol to show it is a request, and a symbol to show it is a data request, and those symbols could be used too in the plugin, and I could background them with green once successful, orange when in progress, red, when unavailable, that sort of thing.

**Comment by markmacgillivray** [comment]
we have bootstrap glyphicons and font-awesome icons too of course, so the real value of this would be to have our own set of action icons and graphic visualisations to go with things like the getting started instructions. Some oabutton theme.

**Comment by JosephMcArthur** [comment]
Okay, we've been asked for a prioritised list of jobs here. 

1) Frontpage / site graphics
 - [ ] Tiny icons for support / about links?
 - [ ]  Download header bar
 - [ ]  Login header bar
2) Sign up process / instructions graphics
 - [ ]  Email graphic (e.g Slack graphics)
 - [ ]  Simple email template(s) including buttons etc
3) Plugin graphics
 - [ ]  Article + Data graphic
 - [ ]  Success, request found, failure 
4) Request system graphics
 - [ ]  a generic symbol for a Open Access Button Request, or just a "request"
 - [ ]  a generic set though like new, moderating, progress, waiting, success
 - [ ]  a graphic set for the actions we might want people to take
5) Aligning / tweaking any graphics we already have
...
Throughout) General style guide
 * This should be done as a webpage / repo / folder (with readme) where we can grab real links to logo's, fonts, colors if needed and share / update easily. 
 * Can be built / collated throughout the above. 
Throughout) General style / structure input
 * Sam as designed whole sites in the past, is input might be quite helpful throughout. 

I'm listing as areas first since I expect the actually needs will evolve and change, so this is a more general approach.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you take a first look at the above and give any input before I send it along to the designer. I should be able to sit with the designer throughout to provide fuller input.

**Comment by JosephMcArthur** [comment]
Have just updated master list to reflect that we're aiming to push the site far ahead of plugin

**Comment by JosephMcArthur** [comment]
Other new big things:

- [ ] Getting Started Graphics

**Comment by JosephMcArthur** [comment]
Got another session (probably the last for now) lined up with the designer this Wednesday. 

In that session, I'll ask him to think about:

- [ ] For institutions page
* graphics in my last comment
- [ ] Request pages / request landing page
- [ ] Error from the backend plugin page / icon
- [ ] A rejig of our style guide

**Comment by JosephMcArthur** [comment]
Okay, this issue has more than fulfilled it's purpose. Some things still to do but I'm going to make a new issue for them!

**Comment by JosephMcArthur** [comment]
Wait, I don't have confirmation from @markmacgillivray that the new prompt & designer are in! Sorry!

**Comment by chealsye** [comment]
@JosephMcArthur Where are the icons at?

**Comment by JosephMcArthur** [comment]
In backend files, under Icons.
