### ISSUE TITLE
Changes stories to requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#207]
Question on if we need to ask users before doing this. Potentially change without emailing the author.

**Comment by chealsye** [comment]
I don't think we need to ask users. The stories were submitted alongside the paywall flag, displayed publicly already. It's effectively just a shift of display and naming, right? If we do choose to email the author we should verify it's a quality story, of course.

**Comment by JosephMcArthur** [comment]
Pretty sure I agree with you here Chealyse. We should notify folks via email that this might be happening though, which we can do en-mass.

**Comment by markmacgillivray** [comment]
This issue then requires no further work - the data will change over when the new plugin and new site are up. So I will remove it from this milestone but not close it, because someone will need to put together an email to all users when we actually do the changeover. Perhaps this is a general issue we should create anyway - email everyone when we make the next release.

**Comment by JosephMcArthur** [comment]
This is on @chealsye 's todo in other places, so this is actually fine to close.
