### ISSUE TITLE
Sign in email issues

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#219]
- [ ] Currently, emails get threaded in some systems (e.g Inbox). Could we add a date to the subject line so that is less likely to happen? @markmacgillivray this seems like a quick & easy fix. 
- [x] When I sign in, I seem to get 2 emails at once. Is this something others can replicate @chealsye @meganwaps @natalianorori . To replicate, simply sign into the site. You should receive two emails, but the code will only work in the most recent.

**Comment by chealsye** [comment]
@JosephMcArthur I just tested it and I only got one email, not two.

**Comment by natalianorori** [comment]
@JosephMcArthur I tested it in google chrome and only got one email as well

**Comment by markmacgillivray** [comment]
Does a different subject line stop them threading? Is this still an issue now that login works better, and only one email seems to be sent? It is not so easy to add a date to the subject line because we are also making a template system to create the emails, so having one part come from a template and another part generating a timestamp adds a complexity.

**Comment by JosephMcArthur** [comment]
Yes, now sign in seems smoother this feels like it matters less. Certainly isn't worth dev time if it's not easy. Closing.
