### ISSUE TITLE
blog.openaccessbutton.org 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#223]
- [ ] Unsecured
- [ ] Leads to a CL api call

```
{
  "status": "success",
  "data": "Cottage Labs API",
  "docs": "Coming soon"
}
```

Should redirect to /blog

**Comment by JosephMcArthur** [comment]
Ah, I see. This is a general odd thing as https://random.openaccessbutton.org/ gets the same response.

**Comment by markmacgillivray** [comment]
Where should this point to, to close the issue? In relation, I would now recommend using medium.com to write the blog instead of having it on the site. This will make blog content easier to maintain for non-technical people, then copy will only have to change on oab_static when it is about the site itself, which, after the main launch should become less common. I think the only concern of not having the blog on the itself is that of the google search ranking due to lack of site changes, but actually we should have plenty site changes because of new requests coming in. Looking at the amount of past blog posts we had, there were just about as many requests and certainly many more blocks (which now will be more requests). Keeping regularly changing content separate is perhaps an easier project management solution, for little technical loss. Also, there are additional ways via medium.com to generate more interest, so being in that community may be of benefit more so than google rankings from blog pages on the site.

**Comment by markmacgillivray** [comment]
If we use medium.com then blog.openaccessbutton.org can point there if you want, or openaccessbutton.org/blog, or probably both.

**Comment by JosephMcArthur** [comment]
Can we point to openaccessbutton.org/blog for now. That can close this, and we can use the other issue to discuss if this should actually go to medium.

**Comment by markmacgillivray** [comment]
Done.
