### ISSUE TITLE
New Frontpage redesign

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#225]
We've been given a concept for the frontpage refined from our existing elements. We have design files for each of these elements

![front page ux](https://cloud.githubusercontent.com/assets/4953703/18412110/c30438e0-777e-11e6-979e-41daf81039c8.png)

**Comment by markmacgillivray** [comment]
Looks nice. Where do I get the elements? Can you send them to me?

**Comment by JosephMcArthur** [comment]
Everything is here: https://www.dropbox.com/sh/onquy2ny2ag4dr7/AADsjB9eQgYjrolzRIiEVNwSa?dl=0. I'm currently uploading it to Github. 

I'm not sure I'd suggest we do _everthing_ here, but it's certainly a step above what we've got now.

**Comment by markmacgillivray** [comment]
My only concern is still whether it is too widget-centric rather than request-centric. We'd need to know what actually goes in that "gif" hole, because without something sensible we are just filling space for the sake of the design rather than the functionality of it. The walkthrough gif thing could be good here. Overall it presents better than I expected though.

**Comment by JosephMcArthur** [comment]
I think we're imagining a walkthrough in the gif spot. Until the new plugin launches, it could just be the logo or something else inoffensive. 

In terms of widget-centricity, I agree, it's a concern. My way to address it would be:
* a context dependant landing page. If you land on mobile, we'll show you text/images for that, if you land on PC we'll show you that. All can mention the institutional version. That gives a clear first action that makes sense.
* Add a panel directly below, or at least, under the map which is "request" centric, or generally broader. This could be combined with an ask for folks to help us with managing the system. That will keep it front and centre for anyone who cares even a little bit, but keeps strong and simple call to action up top. 

Glad it's better than you expected though! I certainly felt like it was a step forwards, but one we can of course adjust.

**Comment by JosephMcArthur** [comment]
@chealsye supports a request panel

**Comment by JosephMcArthur** [comment]
@markmacgillivray we're currently assuming this is the homepage strucure move forwards

Some notes on the design:

* Copy on this page isn't suggested.
* Contribute is currently "explore requests". This term should actually be used over "explore requests" IMO
* About page should be in the nav
* The extra footer section here isn't required in this build

**Comment by JosephMcArthur** [comment]
Here is an updated version of this with an about section, which aims to get at the request stuff, and a optional section for institutional stuff.

 ![front page ux](https://cloud.githubusercontent.com/assets/4953703/18549604/65c7df0c-7b47-11e6-95b7-d83597db729d.png)

**Comment by chealsye** [comment]
@markmacgillivray How much of this design mockup are you using for the new design for next week and next month? Are we using that book image? That logo? Tab icons?

I think, if Joe agrees with my copy, we could keep it to that minimal one block/panel AND include requests. But we need to figure out another colour likely for one of the dark blues or move the features on grey block up.

**Comment by JosephMcArthur** [comment]
For next week we should remove the "packages" bit, and replace it with the about bit.

**Comment by chealsye** [comment]
I'd love a how to gif, but perhaps it'd be better to wait until things are finalised. 

In the mean time formatting it in the centre is a simple solution… but something there would be best. What user stats do we have?

**Comment by chealsye** [comment]
@markmacgillivray FYI - all the copy for the website is in this Google Drive folder: https://drive.google.com/drive/folders/0B3zC2zJzpxoIRm9KS1pKcFVfT3c
@JosephMcArthur has to clear copy still, but the team page can go up whenever.

**Comment by markmacgillivray** [comment]
The old book image in the repo is 1.4MB large. That does not seem like too good a way to build a first page experience, particularly when @JosephMcArthur you were so concerned about page load speed in the past. I can try editing the image and reducing the quality down as far as possible, but that could have some effect on visual quality, of course. This is probably because we are still just mocking up at this stage, but in order to ensure we can use these designs effectively in future we will need images, icons, etc to be as small as possible to maintain page speed. Either that, or we stop caring so much about how fast things like js and css files load, given that their comparative size is less than a tenth of this one image file. Of course, it is only on the first view of a site by a new user that this really matters, because after that their browser will cache the image - but then, the same is true of the js and css files too, hence I just thought I would bring it up, so we can clarify which approach we are taking.

**Comment by markmacgillivray** [comment]
Hmm, actually the old book image does not seem to match what is in the mock up - it may be the original image used to generate the mock up, but it has different filters added to it, to lighten and fuzzify it, it seems. In order to use this I would need the altered image, cropped to size and scaled to the focal point we want to actually use on the site. Otherwise I will be spending ages altering images instead of writing code.

**Comment by JosephMcArthur** [comment]
Happy with the copy. 

Will try and get the image for you tomorrow.

**Comment by JosephMcArthur** [comment]
Mark has pushed major revisions to this page now, which are close to this mockup. I count this issue as complete and suggest other issues are made for smaller changes (which are welcome). 

Congrats to all on this, it's a big job!
