### ISSUE TITLE
Proposed refined Logo design

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#227]
Upon looking at our logo the designer immediately noted "this should only have two colors" and produced the below.

![icon_oab](https://cloud.githubusercontent.com/assets/4953703/18424121/4e5f61d2-78a4-11e6-8d83-53b22ec16f67.png)

I must say, I like it's cleaner aesthetic, certainly fits where we're trying to go. Leaving it here as at the back of my mind I know we're thinking about adjusting our name in future. Not urgent to discuss.

**Comment by chealsye** [comment]
It hurts my eyes.

**Comment by JosephMcArthur** [comment]
Any particular reason for that?

**Comment by chealsye** [comment]
Orange is already a rough color and the white curve around the finger is
harsh to my eyes.

**Comment by JosephMcArthur** [comment]
Some more exploratory stuff here. 

![icon redesign 1](https://cloud.githubusercontent.com/assets/4953703/18549685/d5ce63c0-7b47-11e6-845c-8a8dcbcc3c9c.png)

**Comment by chealsye** [comment]
I'm still partial to 1. I feel like anything that is just the lock isn't unique to OAB.

**Comment by JosephMcArthur** [comment]
@chealsye can you make a version of 2 (the current version on the front of the site) where the whitespace around the hand is all black?

**Comment by chealsye** [comment]
@JosephMcArthur Where is the original file (Photoshop or Illustrator) of those icons? The logo I have under repo is fuzzy when I try to work with it.

**Comment by JosephMcArthur** [comment]
https://github.com/OAButton/backend/blob/master/icons/EPS/icon_OAB.eps

**Comment by chealsye** [comment]
Here you go.

![icon_oab_black](https://cloud.githubusercontent.com/assets/9299248/19413438/0a673b3c-92fb-11e6-997a-5f9aea86edf2.png)

Let me know if you need me to put it somewhere.

The single original logo should be on a transparent and then can just be placed on a black background as well.

**Comment by JosephMcArthur** [comment]
Sorry, my description wasn't as clear as it could've been. Give the hand a black outline, similar to in 1, but to fill the space around it that's currently white (so it would be a rather thick line).

**Comment by chealsye** [comment]
Ooohhh. I was thinking it looked terrible, but I was like Joe wanted it... maybe he'll see the error of his ways once there is a visual ;)

So, it doesn't quite work like that. He didn't just make the lock and then put the hand in there with thick white lines. The white bit is actually cut out completely from the lock. No amount of thickening the border would have given you the result you want. See:

![screen shot 2016-10-15 at 17 41 27](https://cloud.githubusercontent.com/assets/9299248/19414366/b08bae5e-9318-11e6-8efc-fbaa81e65ff6.png)

I was able to re-create it by layering three circles. I can modify things in Illustrator, but I don't know how to create a lot. But this seems to have worked. I learned a new tool today because of this.

![oab_icon_orangeblack](https://cloud.githubusercontent.com/assets/9299248/19414417/1f32f7b2-931a-11e6-89db-cb3b6f770bac.png)

This is with a stroke of 2 for the black. Let me know if you want more or if you need another size.

**Comment by chealsye** [comment]
![oab_icon_orangeblack](https://cloud.githubusercontent.com/assets/9299248/19414421/6e280858-931a-11e6-91ca-a9356a47d0a9.png)

The color looks too orange on that one. Somehow it got changed... re-opened the eps, grabbed the color code, and redid it. So hopefully this looks right.

**Comment by JosephMcArthur** [comment]
Done with designer
