### ISSUE TITLE
/request redesign suggestions

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#232]
Below are what the designer has suggested for our request landing page & the request page itself. 

### Request Landing

I'm quite pro this style. However, I would suggest some additions:

* a stronger call to action / explanation at the top as a separate panel. 
* A filter for request type (data vs articles)
* A button to subscribe to requests from certain fields. 

![request landing page ux](https://cloud.githubusercontent.com/assets/4953703/18549724/152d3a46-7b48-11e6-92c6-6eddeb3f3cb7.png)

**Comment by JosephMcArthur** [comment]
I'll probably return to this at a later date with more thoughts & I should probably split the issue tbh.

**Comment by chealsye** [comment]
@JosephMcArthur - What do you need from me for this issue?

**Comment by markmacgillivray** [comment]
Without more metadata we cannot do much more with the /request page. Subscribing to requests from certain fields is possible but is functionality we have not discussed - what is the purpose of it? as in, the actual known user requirement that it solves? The question of what metadata is actually useful is starting to come up now in multiple places, so that has to be answered first I think. See issue #208

**Comment by JosephMcArthur** [comment]
Yes, this design is more something to shoot for - rather than something we can build now. Later, I think it will become important for folks in the community to be able to powerfully sort requests to things relevant to them. 

I'm going to close this issue now - in favour of small specific issues from what we've already built.
