### ISSUE TITLE
Hide & seek with the Site's Stylesheet

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#244]
I can't find the stylesheet in oab_static. Would be helpful to be able to edit that there, or have clear links in the repo's readme to files which live elsewhere.

**Comment by markmacgillivray** [comment]
If you mean the css stylesheet, there is only one, called oabutton.css, and it is in the /static directory of oab_static (at least it is on the new site, in the develop branch).

The site font is currently Raleway which is a google font. Using a google font also requires a link in the site header, this is currently set in the head.html template in the /templates folder of the dev site. It can be changed easily to any google font you prefer - just use their web fonts browser and copy the link they give you and replace the one that calls Raleway in the current head template. Then in the css you declare the font-family you want to apply to the site. This is currently Raleway, and is set in the oabutton.css file mentioned earlier, to apply to the head, body (meaning the whole site, except where otherwise explicitly declared to be something else).

**Comment by JosephMcArthur** [comment]
Got it, thanks! Have adjusted fonts site wide (on develop) to be Monserrat (headers) & Roboto for body.
