### ISSUE TITLE
Cannot log-in on test extension

### ISSUE THREAD

**Issue by meganwaps** [OAButton/backend#252]
Just ran a user test with someone who currently uses the button and we discovered that she couldn't even log in on the test extension or on the test site:
This user was on a Mac with the latest iOS installed
Using the most recent update of Chrome
In order to reproduce, install the extension using the instructions in the Unified_extension README.md
The user had also just recently downloaded the stable version of the button from openaccessbutton.org, if that helps in the reproduction of this error.
I've included a screenshot of the error itself. 

![screen shot 2016-09-22 at 11 27 03 am](https://cloud.githubusercontent.com/assets/5968703/18760848/950560d0-80b7-11e6-8ad7-faa1b63ad0d7.png)

We tried adjusting privacy settings but still neither would work. Has there been an update or freeze I don't know about?

**Comment by markmacgillivray** [comment]
A current live user would not be able to login on the test extension - the test extension reads from the dev site and the dev data, which does not include the live user accounts. So probably this is not an error, it is just that the user cannot use the test extension because they do not have a dev account. This is resolvable in future user testing by having the user sign up in the dev site first - which has its own issues. I will close this one, but re-open if I have misunderstood and you think this is a separate and ongoing problem.
