### ISSUE TITLE
Return of the Bookmarklet

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#262]
@JosephMcArthur commented on [Mon Jun 20 2016](https://github.com/OAButton/unified-extension/issues/10)

@markmacgillivray has said that "Regarding the old bookmarklet, this should fit with what Steve is doing for the new extension, so that most of it can be used as a bookmarklet too."

If possible, I'd be happy to dedicate a bit of extra time here if it generated a bookmarklet too. Then we get all the cross-compatibility again! 

---

@JosephMcArthur commented on [Mon Jul 04 2016](https://github.com/OAButton/unified-extension/issues/10#issuecomment-230279863)

@Steven-Eardley can let me know if this is possible? If so, assign it a milestone. 

---

@markmacgillivray commented on [Mon Aug 29 2016](https://github.com/OAButton/unified-extension/issues/10#issuecomment-243100807)

Working on this. Even if it cannot be automatically generated, the bookmarklet / widgets will follow the new plugin functionality and style, which is now testable in a web page without installing the plugin

**Comment by markmacgillivray** [comment]
Bookmarklet can be viewed and tested here:

http://oabb.test.cottagelabs.com/

code is currently in new repo called bookmarklet, but actually may be easier to keep it in the oab_static repo. For now it is fine in its own repo.

It should have all the functionality, but some styling still probably needs done, particularly I have not checked the error styling. I also have not actually tested using it, or actually embedding it from an account page on the site, but that won't take long.

**Comment by markmacgillivray** [comment]
Code for bookmarklet has been moved into oab_static repo, because it will be easier to serve it from within the live site URL anyway. The separate bookmarklet repo has been marked as deprecated (and I marked a few others too, we should review at some point and delete many of them).

**Comment by markmacgillivray** [comment]
Bookmarklet page at oabb.test.cottagelabs.com now includes a button that can be dragged to the toolbar to create a bookmarklet. This assigns the bookmarklet to an account on the dev system, but it would not be your own account.

I have temporarily changed the account page to always show the bookmarklet button, and have added to it so that if you use that one instead you will get a bookmarklet that is assigned to your own account.

@JosephMcArthur go and try getting the bookmarklet from your own account page, and see if it works for you.

I have tested and it works for me.

Note I had to change the text content of the button, because whatever the text content of the button is, that is what your bookmarklet gets called - so having it called "drag me to your bar" is pretty uninformative when you look at your bookmarks list.

Note also that if you create a request the bookmarklet will try to open the new request page for you, but it will probably fail because browsers block unexpected popups these days. However, that is exactly why we have the message show up in the bookmarklet too, and you can click the button to take you to the request page instead.

Lastly, as we know, using this on a web page will likely trigger an allow/deny request to the user to share their location - there is no way round this for a bookmarklet.

If this works for you, let me know and I will change the account page back to only show the bookmarklet when appropriate, and then this issue can be closed.

**Comment by JosephMcArthur** [comment]
Okay, I've had some fun with it doing bits on chrome. I have to run for an hour or so, but some notes:

- [ ] I'm yet to be asked for my location despite making & supporting requests
- [ ] A few links aren't colored correctly (e.g after making a request)
- [ ] the title & logo are slightly out of alignment. 
- [ ] I didn't see an example of the bookmarklet taken via the test page working - but from my account it was a-okay
- [ ] the name of the bookmarklet should appear (when installed) as Open Access Button. We'll need to put a bit of copy above the button on download. 
- [ ] it didn't work on my fav test paper: http://science.sciencemag.org/content/293/5530/629 our friend "links not opening on click" was back but it seemed like you were changing things at that point (styling, mostly) so I'll come back & test later. 

please keep it always on account pages for a bit longer. 

Broadly, it seems to work. Although, I had to turn off privacy badger to make it work, as it said it was tracking me.

**Comment by markmacgillivray** [comment]
Just assigning some things to you where I think I am waiting for your response, to keep track of where things are at. I am also out this afternoon, so may not be able to answer until about six. With this one I am not sure what action you want me to take next, or if you intend to test more.

**Comment by JosephMcArthur** [comment]
- [ ] error image doesn't work

<img width="357" alt="screenshot 2016-10-25 16 24 26" src="https://cloud.githubusercontent.com/assets/4953703/19692392/ae299bbc-9acf-11e6-8433-2a5ccf8ac199.png">

**Comment by JosephMcArthur** [comment]
This is changing as I work, are you able to directly push updates to it? If so, that's pretty good.

**Comment by JosephMcArthur** [comment]
I'm still testing, but leaving notes incase you weren't around long.

**Comment by JosephMcArthur** [comment]
Just realised I've done my testing on Chrome - where we're not making this availiable. 

*headdesk*

**Comment by markmacgillivray** [comment]
The bugs above should be fixed as far as possible. I think we can't do any more about the location requesting - I don't get asked either, it seems, but perhaps occasionally. Maybe it just remembers more... Anyway, everything else should be OK. Layout issues may still crop up, we should just fix them as they get reported now.

I have left the checkboxes unchecked so you can go through and test if you want.

NOTE: to make sure you get the latest bookmarklet code, delete the bookmark from your bookmark bar and get it again from your account page (not the oabb page - doesn't matter if that one works because it was just for initial testing, so I have not updated it). Once you get this new bookmarklet from your account page, then it will autoupdate itself in future. (Although of course when we switch to live, you won't be able to use it against live - it will be tied to your dev account.)

@JosephMcArthur pinging you in case you want to look over it again.

**Comment by markmacgillivray** [comment]
There is now a div in the site account page where a blurb about how to drag the bookmarklet button to your bookmarks bar works

**Comment by JosephMcArthur** [comment]
@chealsye have given you a final todo above. When we have an issue for that this can be closed.

**Comment by JosephMcArthur** [comment]
Okay, making the above todo into a new issue. Isn't helpful to keep this big one around for that.

**Comment by chealsye** [comment]
> the title & logo are slightly out of alignment. - @chealsye can you use your keen formatting eye on the new bookmarklet (2.5) to make an issue out of this.


@JosephMcArthur You created an issue for this - #391 in which after seeing the problem I said it wasn't something I could fix. It's text and not an image.
