### ISSUE TITLE
Copy changes to request page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#276]
- [x] Add your support. The reason I have this here is because we don't make totally clear what this actually means, and what will happen when you do.  
- [x] Bottom text block
- [x] Text in story box should be as in #217 
- [x] Should remove donate text until that page works

**Comment by chealsye** [comment]
@JosephMcArthur The bottom three items should be you or @markmacgillivray. Pretty good chance I'll break something if I mess with the request page myself.

OK there's a lot here - apologies about that, but let me know if bits are confusing.

Current page for an individual request:

![screen shot 2016-10-15 at 22 46 22](https://cloud.githubusercontent.com/assets/9299248/19415243/4f432724-9338-11e6-91a6-f1ef704117e8.png)

![screen shot 2016-10-16 at 00 37 23](https://cloud.githubusercontent.com/assets/9299248/19415250/c66a1dbc-9338-11e6-9bd0-bffad582d7dc.png)

Explaining support copy (should go below add your support and above any login or prompt boxes, since it needs to appear on both logged in and not views):
"Do you also need access to this research? Add your support! Requests are more likely to be fulfilled when multiple people need access to the research. Together we can make this a successful request."

@JosephMcArthur, let me know what you think about this. I think its lacking some pizazz...

-Put "Optional" at the end of prompt.
-Is there a reason we should use a conditional sentence with "may be sent" rather than will?

Here's some comments to the current request page. 

![screen shot 2016-10-16 at 00 20 37](https://cloud.githubusercontent.com/assets/9299248/19415220/6a63db80-9337-11e6-9ab0-637c179c5f04.png)

![screen shot 2016-10-15 at 22 46 51](https://cloud.githubusercontent.com/assets/9299248/19415237/1e776e52-9338-11e6-9956-386c616fe42d.png)

"Thanks for wanting to support this request! You need to create an account first. Sign up now to begin support requests and creating your own.

Already have an account? Login now!"

...although this appears whenever someone just looks at an individual request - not necessarily because they are seeking to support it. Should it instead be "Thanks for wanting to support this request! You need to create an account first. Sign up now to begin support requests and creating your own.

Already have an account? Login now!" ?

Too much of a bottom text block. @JosephMcArthur do you want a statement to still be included at the bottom of the page? If so, I'd like to keep it to about two sentences. We can work out a strong statement and always link to a blog post.

![screen shot 2016-10-16 at 00 21 16](https://cloud.githubusercontent.com/assets/9299248/19415211/187facae-9337-11e6-913c-45f38e73cb2b.png)

Are we not able to have drafts of tweets and FB posts when share is clicked? If we can, the suggested copy for those is in #226. If not, I've added some copy suggestions.

**Comment by markmacgillivray** [comment]
I actually just pushed some changes to the request page. I have gone back and added as much of this copy as I can. You will see I have moved the share buttons anyway, so they are no longer in the one big button under support. The facebook one automatically includes the URL but no text, there does not seem to be a way to send text to facebook via their sharer link. The twitter one includes text and the URL, for now I have set it to say "Help us get access to this research!".

I have removed the big blurb of text from the bottom. I have fixed the email spacing in the details section. I have added the explanatory sentences to the add your support section and changed the login sentence.

I have not taken out the sentence about "if you have the right to share it" because I added that because we can only share things people have the right to share - I thought this was added by instruction, but if you really don't want it in any more I can take it out.

I removed the donate sentence.

I moved optional to the end of the story box placeholder text.

I have not made the DOI a link because the DOI does not necessarily go to the same place as the page the request was started on. However the article title text is already a link to the page the request was started on - hover over it gives underlining, and the usual little click hand to indicate it is a link.

**Comment by JosephMcArthur** [comment]
> Explaining support copy (should go below add your support and above any login or prompt boxes, since it needs to appear on both logged in and not views):

> "Do you also need access to this research? Add your support! Requests are more likely to be fulfilled when multiple people need access to the research. Together we can make this a successful request."
@JosephMcArthur, let me know what you think about this. I think its lacking some pizazz...

I agree, it is lacking something, but, it's a great start. 

- [ ] adjust support c2a.

> -Is there a reason we should use a conditional sentence with "may be sent" rather than will?

I did that originally, technically it only may be sent. I did mean to remove it though. 

- [ ] Remove may for will.  

> Too much of a bottom text block. @JosephMcArthur do you want a statement to still be included at the bottom of the page? If so, I'd like to keep it to about two sentences. We can work out a strong statement and always link to a blog post.

I think a statement is important, but I agree we can make it shorter. I think two sentences and a link to a blog, or generally page outlining the request system, works.

**Comment by JosephMcArthur** [comment]
> The facebook one automatically includes the URL but no text, there does not seem to be a way to send text to facebook via their sharer link.

This can be done, but you have to sign up to the FB dev program.

**Comment by chealsye** [comment]
The reason I think "If you have a right to share it" should be removed is because "Can you provide this content? If you have the right to share it, we'd love to hear from you. Please contact us to discuss providing a copy." has repetition. We don't need both of the last two sentences. 

The discussion was about who could provide us a copy, who'd have the ability to provide that link. There's a difference between the contacted author having a link to submit the link to fulfil the request and anybody being able to do that. This instruction is asking to start a conversation. We can cut "Please contact us to discuss providing a copy." instead, but one of the sentences should go.

**Comment by chealsye** [comment]
@JosephMcArthur I'll have a think more on adding some pizazz to the text later today. 

Thanks for clearing up about the may/will. It's true that it may be used and not definitely - but the will is just emphatic, more sharper, which is useful when asking someone to take action.

I'll work on bottom two sentence text either tonight or tomorrow. This can be one of our blogs in the next couple of weeks if we want to explain more, but also would be nice to have such a blog as a way to connect more with the community and get them excited. The text that was there did a good job of that, but it was just a lot.

**Comment by JosephMcArthur** [comment]
May to will has changed.

**Comment by JosephMcArthur** [comment]
Hey @chealsye any thoughts on the bottom of the page's copy & pizazz for the support section?

**Comment by chealsye** [comment]
I have no pizazz to add. There was too much other copy to be doing right now.
