### ISSUE TITLE
Fix the color of the quotes on the home page

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#278]
It looks like the quote cut off has been fixed (yay!) but the quote color has changed to a near impossible to read blue. Just needs to get changed back to white.

![screen shot 2016-10-13 at 10 59 19](https://cloud.githubusercontent.com/assets/9299248/19356700/5255047e-9134-11e6-9905-65a9191e401b.png)

**Comment by markmacgillivray** [comment]
I believe the quote colour has occurred after your commits, not mine.
Because there is presumably an error further up the page where the content
alignment is being thrown off, this could potentially also be affecting any
content below it, by allowing css definitions to cascade to parts of the
page where they should not be. Please check the edits made to the content,
and once those are fixed I can then check the code if there is still a
colour issue.

**Comment by JosephMcArthur** [comment]
Fixed this, was indeed an issue above.
