### ISSUE TITLE
Remove advocacy from footer

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#279]
Advocacy needs to be removed from footer. Couldn't figure out how to do it myself.

![screen shot 2016-10-13 at 10 59 32](https://cloud.githubusercontent.com/assets/9299248/19356737/6f819a6c-9134-11e6-9ffb-5acd7fdd230d.png)

**Comment by markmacgillivray** [comment]
There is a file in the templates folder called footer.html, in there you can find the advocacy link and remove it, and edit any other footer content you desire. Similarly there are other templates in there that can also be edited.

**Comment by chealsye** [comment]
I attempted to do that last night before posting it on github. When I open footer.html in the templates folder it is blank.

**Comment by markmacgillivray** [comment]
Here is the footer file with content in it on the develop branch on github:

https://github.com/OAButton/oab_static/blob/develop/templates/footer.html

Are you looking at the file locally or on github? If local, try doing a git
pull (although that should be up to date, because that should be done
before any pushes anyway, but just to check).

**Comment by chealsye** [comment]
I was looking at the file on github. 

Thank you. Removed it.
