### ISSUE TITLE
On homepage split "seen on" logos so their responsive

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#280]

**Comment by markmacgillivray** [comment]
Did the designer have these logos separately? I asked before when putting
them up there, but all I could find was one whole image which I cut that
out of. To implement designs like this long term, we need the individual
images provided so that I can quickly use them where necessary - it is too
slow a process to have to chop out the relevant bits. I could do it in this
case with these company names, if they cannot be provided individually (and
at reasonable scale and data size) from the designer, but don't have time
just now.

**Comment by markmacgillivray** [comment]
Ah, found them in the assets folder, which was not there three weeks ago, when I last updated the front page probably. Will use them.

**Comment by markmacgillivray** [comment]
Done on dev, no testing needed (they're split, they respond on mobile, that as exciting as it gets), will close.
