### ISSUE TITLE
Impactstory now has a great OA resolver too

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#303]
From Heather:

> We are launching the new API and resolver during OA week, and wanted to give you a sneak peek :)
> We think you should be able to use it from the OA Button really easily!  It's live now, so you should be able to easily drop it in to wherever you are currently looking up full text links.
> oaDOI is an alternative DOI resolver that gets free fulltext where available, instead of just an article landing page.
> - normal DOI gets you a paywall page: http://doi.org/10.1016/j.tree.2007.03.007 
> - our oaDOI gets you a PDF: http://oadoi.org/10.1016/j.tree.2007.03.007 
> - and the API gets you JSON data and the license: http://api.oadoi.org/v1/publication/doi/10.1016/j.tree.2007.03.007 

This sounds like there are a few improvements over what we're using, including I assume those included in http://blog.impactstory.org/find-and-reward-open-access/. 

I think a use endpoint for this would be ideal. They have some interesting things going on, including:
- Straight to PDF links, this seems super handy for us
- Looking at pre-print repos (sounds good, I'd like to know a bit more)

**Comment by markmacgillivray** [comment]
We can do all the same things already, apart form searching datacite for data, because we just have not done that one yet. BASE / dissemin already returns PDF links, and I already have code for finding PDF links on journal pages if desired, and we already have a CL app for calculating the licence of something.

So whilst technically possible in numerous ways, at some point there is some strategic decision to make around which methods to use, and probably something to consider around whether or not to launch another OA doi resolver - we've had a CL one now for quite some time, but have not told people much about it because there was also talk of an oabutton/dissemin resolver, and those possibly being the same. I'm pretty sure I heard about the impactstory one a while back too, so which to go for? Theirs, our own, another one... things to think about.

**Comment by markmacgillivray** [comment]
Unassigning for now, no clear need for it. Leaving issue open for later review.

**Comment by JosephMcArthur** [comment]
@markmacgillivray  did you look into the "custom list DOI prefixes, to see if it’s in a known preprint repo" to see if that would be useful for us? I'm happy to ask them about this.

**Comment by markmacgillivray** [comment]
@JosephMcArthur did they publish it anywhere? If they are happy to provide it we can use it too. If they are updating it regularly then a URL to where we can get an updated copy would be more useful. Or we can compile our own - ask preprint repos what their prefix is, or infer it from their publications.

Note though that this is not a foolproof method - a DOI prefix does not guarantee that a publication is owned or maintained by the publisher that is assigned that prefix.

**Comment by JosephMcArthur** [comment]
I've asked them for more info on this.

**Comment by JosephMcArthur** [comment]
Okay, the code for this is here: 
* https://github.com/Impactstory/oadoi/blob/master/oa_local.py#L84
* https://github.com/Impactstory/oadoi/blob/master/oa_local.py#L17
* https://github.com/Impactstory/oadoi/blob/master/oa_local.py#L200
* https://github.com/Impactstory/oadoi/blob/master/oa_local.py#L84
*https://github.com/Impactstory/oadoi/blob/4de92611610def94e9c5e8e9f27fde534f78eb13/oa_local.py#L105

and "basically we've hardcoded some lists and consider those urls/dois open.". 

@markmacgillivray if any of these are help for us then please do what you can to prioritise & implement. Otherwise, please feel free to close.

**Comment by markmacgillivray** [comment]
This is mostly a straight lift of everything on the datacite page of DOI prefixes that have submitted to datacite. There are some errors in what appears to be the method they used to scrape the prefixies, resulting in things like 10.61 instead of 10.6100 - as it stands, and as it is used in this code, this is likely to result in misinterpretations of certain prefixes. This could be fixed quite easily, if we were to use these datacite prefixes. However, it is also not clear that just because the prefix is in datacite that it links to an item that is not closed access. Having a quick look, I can fairly quickly find one that is listed in datacite that does not appear to be open:

https://www.thieme-connect.com/DOI/DOI?10.1055/s-0033-1340471

The preprint URLs and open data URLs would probably work accurately, but given that they identify sites that we can already identify as open, I do not think there is a benefit to us including these.

Finally, given that DOI prefixes do not necessarily indicate the publisher the article belongs to, there is always the inherent risk that identification by DOI prefix will be incorrect. This could be overlooked if there was sufficient benefit to doing so, but given the above points, I don't think there is at this stage.

So I will close this issue for now. Could be revisited if we hear from impactstory that they have a better list in future.
