### ISSUE TITLE
Put up /requests received page 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#337]

**Comment by markmacgillivray** [comment]
@JosephMcArthur although this is what I intend to do next on my task list, it is also actually an issue which should perhaps be reconsidered in relation to the 3.5 milestone review. Is it OK for me to just make such a page, even with old content, or should it start with Chealsye doing some copy? If it does not start that way, is it clear how anything that I do will fit in to other plans for copy / user testing the response page once I am done? Something to discuss on the next Monday meeting.

**Comment by markmacgillivray** [comment]
@JosephMcArthur as this issue has the Blocked: Copy label, should it really be assigned to me yet? I do want to get on with it, but if that is not suitable for the team overall, then I can work on other things.

**Comment by JosephMcArthur** [comment]
Given timelines, I think in this case it makes more sense to get up a page
with functionally working (with old content) and then we'll work within
those restrictions to improve copy where possible.

**Comment by markmacgillivray** [comment]
I have put up a page for this, although functionality in the backend is still in progress. However for now, there is a page where ALL content that it would display can be seen, every step of the way (which of course would only display relevant sections depending on article type and stage in process). This should make it easy for now for anyone to look at the copy that is in there, and write up what would be preferred in each panel. Each panel has a name, so easy to reference from this issue in further comments.

I will continue with the functionality, which should be ready tonight, but will leave the page displaying all sections anyway so that content can be reviewed.

Specific information about validation and providing badges is NOT in this page, because it will make more sense to show them on the request page itself - once content is provided, URLs can be added to requests that are at the "received" status, along with asking users to validate. Once validated, the badge link info can be displayed too, so the author can get it.

@JosephMcArthur @chealsye this should mean you are not blocked on checking / creating copy for this, but will keep this one assigned to me because I continue to be responsible for finishing it off.

**Comment by markmacgillivray** [comment]
By the way to see the response page, go to any open request when logged in as admin, and you will find in the details section there is now a "responder" button that will take you to the response page for that request - this is the page the authors would receive a link to when we email them.

**Comment by JosephMcArthur** [comment]
I have taken a first pass at copy for this, and will continue to do bits as I have time. I'm trying to make sure each part has the info required for the system - but not so much that it sounds good. @chealsye, if you can ensure the later that would be great. Assigning.

**Comment by markmacgillivray** [comment]
@JosephMcArthur @chealsye later today I can finish the functionality for the actual submission on this, but to do so I will start hiding the sections so they actually function. You will still be able to see all the text though by looking at the underlying page code, which is in the repo, at:

https://github.com/OAButton/oab_static/blob/develop/content/response/item.html

(or if you pull a local copy to work on, then in the same place on your local copy - in the content folder, under the response folder, the file called item.html)

So at some point you may see that the response page is changing, and that you can no longer see the full text - so just look at the file instead.

Once the page is done for functionality and copy, presumably we still want to get it tested. I propose that each week we review at our usual weekly meeting what is ready to test to go live, then after that meeting as soon as it is tested it can be pushed to live.

**Comment by JosephMcArthur** [comment]
I took another go at copy yesterday, it's better now.

**Comment by chealsye** [comment]
Sorry - just not getting to this. What is the url for this page? http://oab.test.cottagelabs.com/request/received? I want to make sure I'm looking at the right then and I'm not sure. Thanks!

**Comment by markmacgillivray** [comment]
@chealsye there is not one specific URL, it is a page generated for each request. It would be at http://oab.test.cottagelabs.com/response/<RESPONSEID> but you can more easily get to it by logging in on the dev site (your account has admin rights) then just view any open request. In the "details" section of the request, you will see a new button called "responder" - click that and it will take you to the corresponding response page for that request.

**Comment by markmacgillivray** [comment]
Make a URL the default way an author provides content, and the page copy will explain that it must be available publicly at that URL and it must be allowed for the author to provide the content.

When a URL cannot be given, e.g. the content is not yet publicly online anywhere, it can be uploaded, and again the page copy must indicate that the author has the right to do so.

The author must also agree to provide as cc-by for articles or cc-zero for data, and they should check a checkbox agreeing to that and to having the right to share the content.

When we receive a file we will send it to OSF for data and Zenodo for articles (the page copy already explains this).

Zenodo review all submissions and require a title and description, so add a title field (which can pre-populate with article title but will allow the author to change if necessary) and make the title field and description field mandatory.

**Comment by markmacgillivray** [comment]
Just a reminder, the above comment is a synopsis of recent email discussion on this issue.

**Comment by chealsye** [comment]
Thanks for clarifying, @markmacgillivray.

![screen shot 2016-11-08 at 2 39 25 pm](https://cloud.githubusercontent.com/assets/9299248/20117542/152aab6c-a5cf-11e6-8661-aa88fd43ffa1.png)

> Thanks for responding to our request.
> 
> To fulfill the request please provide a URL to the research content or upload it.
> 
> URLs should go to where the research article or dataset is publicly accessible without restriction. It is best for the content to be stored in a repository where it will be preserved and accessible. 
> 
> If you submit the research content in this form, we will deposit it to Zenodo where it will be preserved and accessible. 

May need to be tweaked again though. But this is where my brain is at right now.

**Comment by JosephMcArthur** [comment]
@chealsye @markmacgillivray what's needed to close this now. I can see it's still assigned to you both, and I'm keen to see this released asap.

**Comment by markmacgillivray** [comment]
@JosephMcArthur last thing I remember is you said you were going to try it last Tuesday and let me know if you think the content is OK (because Chealsye was off last week). It is ready to go, connected to OSF and Zenodo, but does not actually publish to Zenodo because published things cannot be deleted. So once I know the page content is acceptable, and you are happy with how it works, it should be ready to go live.

We can try having Megan do user testing after that, by submitting a URL to an article and a data request, and submitting a file to an article and a data request - I can enable it far enough to save a URL, and also to deposit to OSF, and we can check both those things happen. For files for articles, we can have it deposit to Zenodo but NOT publish, then we can check on Zenodo and should be able to see it there when we log in. I have never used Zenodo for that though, so it should really be user tested before we launch it.

So, there is nothing more from the development side needing done for it, just content sign off then user testing, and I can enable things as required.

**Comment by meganwaps** [comment]
@markmacgillivray @JosephMcArthur I'm on this now. I'll let you know if I'm having any problems or questions.

**Comment by JosephMcArthur** [comment]
Okay, I think this is good to go, although could certainly be better. Will handle that in later issues. 

@markmacgillivray please push this to master asap. Then tag @natalianorori to let her know the system is operational. If both of you could verify that files are being delivered okay, that would be good. @meganwaps if you can reach out to authors a week or two after we send them a formal request to see how're doing, that would be good too (we can make an issues for this & elaborate on what to ask later)

**Comment by markmacgillivray** [comment]
Moving this up to current milestone to keep it in mind

**Comment by JosephMcArthur** [comment]
If this is pushed to live, I think we can close. Correct me if I'm missing something above.
