### ISSUE TITLE
When not signed in on plugin, request buttons take you do blank page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#360]
This is complicated by #324, but usually I can right click & copy link where they're present. 

### Expected Behavior

* Tell me to get an account, or something like that. 

### Actual Behavior

* taking me to blank page

### Steps to Reproduce this bug

* http://www.nejm.org/doi/full/10.1056/NEJM199901143400207 with plugin.

**Comment by markmacgillivray** [comment]
I think that message should always show if the user is not signed up / has not attached their account to their plugin. It doesn't clash with the issue of the buttons being visible and opening nothing because I am fixing that. Now that we are not telling people about API keys at all it makes sense to change the wording so I have changed it to end after "signup or login now".

I will unassign myself because I think this solves the issue, can either be closed or reassigned if there is further problem

**Comment by JosephMcArthur** [comment]
Okay, if this specific issue is fixed grand.
