### ISSUE TITLE
article icon is a bit messed up

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#362]
The "lines" of the document are an irregular shape, and while it's not "wrong" the data icon is uniform and it looks out of place

Original file: https://github.com/OAButton/backend/blob/master/icons/EPS/icon_article.eps

**Comment by markmacgillivray** [comment]
I did not use the one you linked to because it looked worse, so I went with the current one, where yes they are different but that makes it look more like an article - having them regular looks more like data. I can change it to whatever image you want, but I need a png image with transparent background suitable for display at about 200px width. These are not things I can do much better than I have done, so unassigning myself. Anyone who can make a better one, attach to this issue and reassign me to put it into the plugin.

**Comment by JosephMcArthur** [comment]
getting this now

**Comment by JosephMcArthur** [comment]
Ta-da!

![icon_article_black](https://cloud.githubusercontent.com/assets/4953703/19628502/eb3a2118-9956-11e6-86d7-0a002e6b6691.png)

**Comment by markmacgillivray** [comment]
Ah, I should also have said I shaded them to #333333 so that they looked better on the orange backgrounds - can you make one like this coloured to #333333 ?

**Comment by chealsye** [comment]
![article_333333](https://cloud.githubusercontent.com/assets/9299248/19628878/079f6320-9936-11e6-9cbb-2b8896c634af.png)

@markmacgillivray This is #333333. Let me know if it needs resizing though.

**Comment by markmacgillivray** [comment]
This one is not on a transparent background, sorry, Size and foreground colour is fine though. If you can make the background transparent I can use it.

**Comment by markmacgillivray** [comment]
@chealsye just adding your name to ensure it notifies you of my previous comment

**Comment by chealsye** [comment]
![article_33333](https://cloud.githubusercontent.com/assets/9299248/19628920/22b1376e-9937-11e6-9141-36426b472ae9.png)

Sorry. Of course I can make it transparent - just was saving too quickly.

**Comment by markmacgillivray** [comment]
OK thanks that is in the repo now. @JosephMcArthur is that this issue ready to close?

**Comment by JosephMcArthur** [comment]
Yup, assuming it goes in okay!
