### ISSUE TITLE
Plugin counter changes

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#363]
* I wasn't sure if you could submit after the first 5 words. Not suggesting a change, just a datapoint
- [ ] parts of the counter don't always count. E.g "5 more words" is still 5 until it switches. This is a bit confusing. 
- [ ] Eventually, the message stays the same no matter how many words you right. 

Many of the above issues can be dealt with through #319. However, they could be solved in other ways and so am putting here.

**Comment by markmacgillivray** [comment]
This has been fixed, there was an error after 20 words. it does stay at five more words, because that is just the suggestion of how many more to write. These could be changed, but probably has to be a later milestone, this is the text that was agreed to already, I believe. We are running out of time to keep making changes (really we are out of time already). Unassigning myself as no technical issue remaining.
