### ISSUE TITLE
Unclear why there is no location for this request

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#365]
http://oab.test.cottagelabs.com/request/9wXFSWMcTLaFeWE2W

**Comment by JosephMcArthur** [comment]
To be clear, it's unclear because others had it!

**Comment by markmacgillivray** [comment]
Unknown, it just worked for me. We know that sometimes the browser fails to find your location - there is nothing we can do about that, but we now have it coded so at least that does not cause a failure, we just don't get location. This is the first one I have seen on the new plugin where we did not get it though. But I think we should close this issue as there does not seem to be any ongoing problem. Re-open if you think otherwise.

**Comment by JosephMcArthur** [comment]
Fine to close. Have suggested we monitor it here #367.
