### ISSUE TITLE
Refactoring & Commenting the plugin & bookmarklet code

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#374]
This is a holding issue for @markmacgillivray to think about what can be done to make it easier for him to maintain the plugins & bookmarklet moving forwards. Time to refactor & comment without bug fixing or enhancements is important.

**Comment by markmacgillivray** [comment]
Bookmarklet now uses the same core oab.js and ui.js files as the plugin. Apart from those, the bookmarklet README file explains how it calls them via includer.js, which itself is just a few lines of code that also pulls in some css.

The Plugin code itself follows the structure of a chrome extension, documented in the chrome extension documentation. The main functional code in oab.js and ui.js includes commenting to explain what each section is doing, and has function names that explain what they are actually doing.

Closing this issue having reviewed, and finding things seem to be understandable now that plugin and bookmarklet have merged, and plugin has since been updated and had improved structuring.

**Comment by JosephMcArthur** [comment]
Fantastic, thanks for adding the documentation <3.
