### ISSUE TITLE
OA Week Release Retrospective

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#382]
An issue to drop notes in prior to a discussion. 
- What can we do better? 
- What went well, what didn't? 
- Anything we should change in future? 

This is for all @OAButton/team

**Comment by JosephMcArthur** [comment]
Some quick notes:

* Testing each version takes too long. Automated testing via browserstack? 
* I'm Unaware of major technical barriers - needs to have issues that reflect this
* Unaware of size of issues, estimation important? 
* Unclear definition of what "working" is. 
* Wasn't good at managing scope creep in weeks leading up to release.

**Comment by markmacgillivray** [comment]
Adding / responding to notes:

* I'm not sure automated testing will help in our case - the breaks come from either new functionality (which breaks the same on any browser) or content changes (which break things accidentally but not necessarily because of browser compatibility. The only place where testing on different browsers really paid off was for the bookmarklet, and browserstack-style testing would not help there because it is about injecting code into other peoples websites rather than our own.

* I think the technical barriers / size of issues is more related to size of issue in the overall rather than technical sense - we've had technical barriers come up where I've not been able to get to basic technical things soon enough because of ongoing work, and I think that is where we need to be clearer about the size of issues - what they involve in total, where they start, what can be done when.

* The above relates to scope creep, and is also something I have let happen too much as well - it is desirable to want to get a lot done quickly, but it impacts on other people in the team, so milestones MUST remain fixed to what they were when they started, and when they start they have to be reviewed and ordered to make it clear who is doing what first.

* This should make it clearer that things are not so easy, and that we just have to wait to get all related parts of an issue done before moving forward. We will have to work slower overall, but that is the only option if the JIT mentality does not work well for the team.

* With milestone 4 moved out by a week, on our Monday meeting coming up we should review what is in the milestone and ensure everyone knows where things are starting, and that nobody goes on ahead until earlier parts are completed.

* (Also actually now that the main site is up, the most complex part really IS over - but yes, don't assume that means things are easy, but keep in mind increased complexity of issues as a whole.)

**Comment by JosephMcArthur** [comment]
@meganwapes can you set up an hour for the Chealsye / Mark / Natalia & I to talk about this in the next two weeks. 

- [ ] arranged retrospective meeting

**Comment by meganwaps** [comment]
@JosephMcArthur no problem!

**Comment by JosephMcArthur** [comment]
from #395 

> @JosephMcArthur for things like this, worth deciding the process you want for making the change - e.g. usability test, new copy, then additional functionality, make the changes, put on dev to trial it, then put to live when happy.

**Comment by JosephMcArthur** [comment]
General thoughts:

* We were 2 weeks late on release (kinda), but the release seems (major) bug-free. This was in line with the decision we made to have our v3 release be good, not timely (rather than the other way around, our usual approach)
* I don't know how to deal with bugs in agile
* We need clarity on what different signals (labels / assignment) mean to different people
* We need to engage more full as a team from a copy / technical perspective from the mock-up phase
 * We need to create mock-ups as a habit, not a one off (and can, we have money!)

**Comment by meganwaps** [comment]
Some of my thoughts I'd like to discuss during the meeting: 

-Lack of communication at times, or underestimating how long my work will take. 
-Sense of urgency on my part. (I didn't have it until Joe lit a fire under my butt) 
-Lack of fanfare
-No response beyond Joe regarding the user testing. I'd like feedback from everyone ideally. 
-Time difference, I'm willing to stay up or wake early to get things done while we're all awake. Just need to know. (connects to communication issue)

**Comment by JosephMcArthur** [comment]
@markmacgillivray Do you have anything you'd like to improve from this release?

**Comment by JosephMcArthur** [comment]
@natalianorori are you able to take some notes from this? Perhaps booting up a Gdoc & posting here would be helpful

**Comment by JosephMcArthur** [comment]
Other thoughts:
* Mark & I occasionally IM'ed, which was useful. Others may benefit from this and we could try and move those chats into a more open space

**Comment by markmacgillivray** [comment]
I'd like to make sense of how everyone expects github issues to work during a sprint, to clarify who gets assigned things, and how bugs are handled, and to ensure we all agree that any contributions are about moving the project forward (assume positive intent).

**Comment by JosephMcArthur** [comment]
Call Notes here: https://docs.google.com/document/d/197wuP6dlCXa0XWD5vbwo2NLSuiuyqIXCvxVu7M70ioY/edit

**Comment by JosephMcArthur** [comment]
To put something in the what went well column:
* We user tested things before they went out!
* We are still working on the product & releasing bug fixes and improvements
* We have a solid dev / live split & deployment process

**Comment by chealsye** [comment]
-Lack of clarity/communication at times
-Help needing getting lost amount long threads
-Feeling like things needed to be immediately done when they weren’t a known task 
-There were a lot of little, sudden things needed right before launch that weren’t known/discussed prior and seemed to pop up
-Plugin was ready 18/19 days after promised, which left us also we little experience
-Often I felt like I did not know what was happening, how features would work

**Comment by JosephMcArthur** [comment]
Closing, but adding a "Meta" label, for discussing / identifying topics like this in future.
