### ISSUE TITLE
Firefox Bookmarklet Update

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#385]
- [ ] asked for location, but is said the site I was on was asking, not the bookmarklet. Hope this can be addresses, it's confusing. 
- [ ] seems to ask for the address twice if you submit a request. Once when you open the bookmarklet, once when you're submitting. 
* was able to open links, unlike previously. Could also make requests & other functions. 
* still occasional formatting issues (links a bad color, text boxes out of page) but that's known. 
- [ ] close button still didn't work at any point
* I generally found it a bit inconsistent when clicking. Sometimes it would open, sometimes it wouldn't. I have no particular pattern of this, need to look into it more, but logging it. 

This is meant to mirror testing done in #262

**Comment by markmacgillivray** [comment]
About the location thing, yes, it's always going to look like it's the website that's asking, because technically it is - the bookmarklet gets injected into the page you are looking at. There's no way round this, apart from the discussed option of just not getting location data from bookmarklet users. There could be alternatives, like grab it once when they visit their account page and just assume they're always at that location.

**Comment by JosephMcArthur** [comment]
I think with the bookmarklet we should look for alternatives long term.
What you've suggested there is a good fix, I'd be happy with it, but
clearly not something to do now.

**Comment by markmacgillivray** [comment]
@JosephMcArthur The above about location are unfixable until we decide what to do about location from bookmarklet overall, and the third is fixed. I'll close this issue, but reopen if you have followup
