### ISSUE TITLE
Bookmarklet not closing

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#387]
X doesn't seem to work on Chrome & FF. 

@meganwaps, can you flesh this out?

**Comment by markmacgillivray** [comment]
This definitely works for me on the newest version

**Comment by markmacgillivray** [comment]
Just tried it again, still working

**Comment by markmacgillivray** [comment]
Ooh, but there may be a bug where if you open the bookmarklet on a page, then close it, then open it again on the same page, it never goes beyond the spinner and the x button doesn't work at that point... technically people should not do this, they use the bookmarklet then move on, but should look into this in the morning.

But, if you are actually not able to close even the first time, that is pretty weird because I can.

If it would help for testing now and in future, I could have the bookmarklet and the plugin actually show their version numbers down at the bottom of their UI, in small letters. Maybe that is useful, maybe not. Can't do just now though, but as long as you have got yourself a new bookmarklet from your account page, you should be on the newest version.

**Comment by meganwaps** [comment]
@JosephMcArthur @markmacgillivray 'X' not working on Safari either.

**Comment by meganwaps** [comment]
@markmacgillivray I'm unable to 'X' out on Safari even when the button isn't on the 'spinner'. It has occurred every time I've used it in Safari. I usually have to just exit the tab.

**Comment by markmacgillivray** [comment]
I've just tested on safari and firefox with a new bookmarklet and the X button works for me on both. I think for now we'll have to go with it as is, and if you can get a video of the issue occurring, I can try to resolve later.

**Comment by JosephMcArthur** [comment]
Okay, it just shut for me on Safari. Didn't try it twice. More testing needed, but yes, hints that this is infact okay.

**Comment by JosephMcArthur** [comment]
@meganwaps have you made any progress here?

**Comment by meganwaps** [comment]
This is no longer an issue for myself on Safari. I suggest we close this issue, unless anyone else is still experiencing this issue?
