### ISSUE TITLE
Not seeing blacklist response when opening plugin on openaccessbutton.org

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#389]
Instead seeing make request

**Comment by markmacgillivray** [comment]
Aaargh I removed the default blacklist when working on the code to update it via google spreadsheet, and have since replaced it, but due to this have now noticed that the fix to the plugin to show the error image properly also actually removes the error text. I'll have to make a new version, and we'll have to update chrome store (not too big a deal because it auto updates anyway, but still) - will make new version tomorrow.

**Comment by markmacgillivray** [comment]
Tested this and it works now with the bookmarklet, so when we push a new version to chrome and it updates for users, they will see it as expected. for now, they will already get stopped, but will get no explanatory text. I have made a new live release version on the extension repo, ready to go to chrome.

**Comment by markmacgillivray** [comment]
@JosephMcArthur this also is currently assigned to me, but I am no longer capable of actioning it. Normally I would therefore assign to whoever I think is carrying it forward (and if my choice is wrong for reasons I was unaware of, that person could assign to the correct person). So for now I am just unassigning myself, as I cannot lead this issue further. Again, something to discuss tonight.

**Comment by JosephMcArthur** [comment]
Fixed in 1.2 release. Closing.
