### ISSUE TITLE
Users need to refresh account page to sync chrome extension with account, but arn't told this.  

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#390]
They're only told when they first open the plugin, which isn't ideal. Seems better to handle when they're in the sign up process. 

When they click the "get my open access button", can a bit of text show up telling them to refresh the page, or similar? Open to other ways of solving this @chealsye @meganwaps @markmacgillivray 

Feels like something is needed though.

**Comment by markmacgillivray** [comment]
I'm not sure if there is a technical solution to this. The plugin does not necessarily trigger on inline install because it is already on the /account page, rather than going to the /account page. I will look into it, but if not possible then some further explanatory text would be required - which perhaps would be useful anyway, I'm not sure that the install buttons are very clear as to what they do.

**Comment by JosephMcArthur** [comment]
@markmacgillivray any update here, or should we handle with a install message as we do for the bookmarklet?

**Comment by markmacgillivray** [comment]
I have added to the code to try to refresh the page after the plugin installs, however because inline install can only be done on the live site we can't actually test this until we next update the live site. So this is done, but keeping open until we do an update, at which point I will check it works. If not, we will have to fall back to using some explanatory text.

**Comment by chealsye** [comment]
@JosephMcArthur @markmacgillivray Is there still blocked copy on this? Or is that just in case Mark's solution doesn't work out when we next update the live site?

**Comment by JosephMcArthur** [comment]
Just in case

**Comment by meganwaps** [comment]
I haven't experienced this issue on a personal level since this summer. Is the chrome restart a 'one time' thing, or do we need to tell users to restart every time they download and updated version of the plugin?

**Comment by markmacgillivray** [comment]
Fixed, the forced page refresh causes the page to reload and then to match the newly installed plugin with the api key, and indicates on the page that it is now available to use.
