### ISSUE TITLE
Logo & Title out of alignment on Bookmarklet? 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#391]
This seems to happen even when the site CSS isn't being a pain.

**Comment by markmacgillivray** [comment]
Have centre aligned now, which looks same as plugin. However, it does still look like there is an issue with the header whitespace not aligning with the right side of the plugin window.

**Comment by markmacgillivray** [comment]
Tried some other pages and now title spilling over into second line. Annoying and fiddly! Will try more bookmarklet css when I get time.

**Comment by chealsye** [comment]
As I told @JosephMcArthur earlier I couldn't test out the bookmarklet, because my Safari browser wasn't functional. I was able to get the Button installed on my work laptop today and saw the alignment issue. This is assigned to me, but I don't think this is something for me to fix.

@markmacgillivray Open Access Button is text and not an image, right? Is it black or the dark blue from our style guide? Looks like the plugin and bookmarklet OAB name looks black to me, but wanted to verify.

![screen shot 2016-10-31 at 2 13 12 pm](https://cloud.githubusercontent.com/assets/9299248/19865895/81164f40-9f74-11e6-95e2-ba2b289e90e0.png)

**Comment by markmacgillivray** [comment]
Hi @chealsye thanks for the screenshot, this makes it clearer what was meant by being out of alignment. Which version of the plugin did you install? Are you using a manually installed development one or did you install from the chrome store?

The header text is text rather than image, yes. I believe the colour is black, as was the old one. Are you expecting it to be dark blue?

**Comment by chealsye** [comment]
@markmacgillivray This was the bookmarklet on Safari. I installed it from the website.

Black isn't in our style guide, so it is surprising to me.

**Comment by markmacgillivray** [comment]
Changes have been made on the dev bookmarklet, so for now my contribution here is done. Normally this means I would assign it to whoever has to work on it next, so it is clear who is responsible for moving it forward, however after discussion at the meeting on Monday, it is no longer clear that assigning is acceptable. @JosephMcArthur I am unassigning myself so I can keep track of what things I actually have to work on, and this can be raised tonight as an issue for how we would keep track of who is owning something at a given time, if not by assignment.

**Comment by JosephMcArthur** [comment]
Megan can you test this on a few sites, should be blue, one one line & align with the logo nicely.

**Comment by JosephMcArthur** [comment]
Megan can you test this on a few sites, should be blue, on one line & align with the logo nicely.

**Comment by meganwaps** [comment]
The bookmarklet appears to be all aligned now, it's also keeping me logged in a lot longer (days) than it used to-which is fantastic because then I don't have to sign in as often!
