### ISSUE TITLE
Add a space on story prompt text between sentances

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#392]
From @chealsye - just didn't want to forget.

**Comment by markmacgillivray** [comment]
@JosephMcArthur @chealsye I don't see anywhere that the story prompt text is lacking spaces. Can you be more specific about where this problem is?

**Comment by markmacgillivray** [comment]
Never mind, found it.

**Comment by chealsye** [comment]
@markmacgillivray Should I be seeing the fix? Because I just used the plugin on Chrome and the space in the prompt is still missing.

![screen shot 2016-11-03 at 22 02 18](https://cloud.githubusercontent.com/assets/9299248/19992104/60cb755e-a211-11e6-86f3-cc043d9362f4.png)

**Comment by markmacgillivray** [comment]
@chealsye it is in the latest code in the develop branch of the plugin, so to see it you'd have to install the develop version of the plugin from the main code of the develop branch.

Do you usually only install from releases rather than the code directly? If so this is a question for how we declare something ready to test - I could label issues with a release label that indicates which release they will be available to test in, then when that release is available you would know that installing that release should show you the fix for that issue.
