### ISSUE TITLE
Broken Request Link

### ISSUE THREAD

**Issue by meganwaps** [OAButton/backend#395]
One of the requests has a link that does not work. 
Upon clicking the article title, we should be taken to the requested article, however this link just leads to a broken link on our site. 
https://openaccessbutton.org/request/saGBPhgdAny8A35iQ

I've included the link, in order to reproduce this bug, you just need to click on the link titled 'Untitled Article'. This is odd because on the requests page, where all requests are listed- this article does actually have a title. This request also lacks a location. 

This is what happens after you click the article. 
This test was done on Safari v 8.0.7 while logged in to my admin account. 

![screen shot 2016-11-01 at 12 50 20 pm](https://cloud.githubusercontent.com/assets/5968703/19904889/ca47fed0-a031-11e6-8a7c-a16ed78423c7.png)

@JosephMcArthur @markmacgillivray

**Comment by markmacgillivray** [comment]
This user created the request on the site, and they did not type in a URL in the find box - they typed in the title of the article!

This must have slipped through the usability testing. We will need an alternative way to make it more obvious that the user should put in a URL there, not an article title. From the technical perspective, I could also block things that don't appear to be URLs and flash a warning.

The reason it seems to have a title on the overall requests page is because that page defaults so showing the URL if there is not title - so, as the user typed in the title in the url box, it is showing up there, although the system actually thinks it is displaying a URL.

@JosephMcArthur for things like this, worth deciding the process you want for making the change - e.g. usability test, new copy, then additional functionality, make the changes, put on dev to trial it, then put to live when happy.

**Comment by markmacgillivray** [comment]
Sticking with the protocol of not adding things to the milestone once it's started, this couldn't be done until the next sprint at the earliest. How long it would take is less relevant than what other things likely couldn't get done within a sprint where we prioritise this over any other issues.

It's a small technical change, but if everything we release is going through some sort of test / content approval on dev, then it has a bigger impact in the time available in any given sprint.

So for now I can't close with a technical fix, not until at least the next milestone. Some sort of rapid response to users, outwith development, would be good though, and perhaps following up with the user will give more insight into why they did what they did, and perhaps indicates that people do want something we don't yet offer, e.g title searching.

I think for now this still seems to me to be needing assigned elsewhere, for these things to happen and to be decided, before then being brought into a development sprint.

**Comment by JosephMcArthur** [comment]
I'd assigned this to the next milestone for you Mark. @meganwaps it would be good if you could respond to the user before that though. 

You mention a good point, this "bug" could represent a feature people actually want. @meganwaps it would be good if you could try and work a question on this into user tests.

**Comment by meganwaps** [comment]
I'll contact that user right now.

**Comment by markmacgillivray** [comment]
OK, this is done on the dev site, things that are probably not a URL to a page on a website cause an alert warning, and do not process. Also strips whitespace surrounding the URL. I will now assign to @meganwaps for UI testing.

**Comment by JosephMcArthur** [comment]
Great! this looks good.
