### ISSUE TITLE
Wait time to receive login email?

### ISSUE THREAD

**Issue by meganwaps** [OAButton/backend#401]
This is more a question than an issue. 
What's the usual wait time for you all to receive your email with your code to login?

It's taking 15+ minutes for my account to receive the email, despite the timestamp saying it was sent immediately. 

Is this an issue for any of you, or is my email just being difficult?

**Comment by markmacgillivray** [comment]
I get them near instantly. If the timestamp says it was sent immediately, then it sounds like an issue at your end. Some mail clients only check every 15 minutes or longer, what do you use? Also @JosephMcArthur has access to the mailgun account where it shows logs of sends and issues, so he could investigate (or delegate) slow email issues that way too (the backend has no further info on mail sending, other than that it sends them to mailgun, which handles sending them on to actual recipients).

**Comment by meganwaps** [comment]
I use Gmail. This time is extremely unusual because it's almost at 30 minutes. Once I receive the code I'll probably have to ask for a new one since it won't be valid anymore.

**Comment by markmacgillivray** [comment]
Are you finding this problem logging in to the dev site or the live site?

Dev site can be slow if I am working on it, because it can be turning on and off. I have been working on it the last few hours.

I just tested on dev and live and the backend is sending the emails straight away, and I am receiving them straight away.

I am also on gmail, I don't see a delay. I think the gmail default time to check for new email is pretty short, I don't remember changing mine specifically, so it is probably not that.

**Comment by meganwaps** [comment]
This is logging in to the live site. 
I just entered my email again and received the message immediately, so I'm not sure what happened last time. I'll close this issue but keep you informed if it occurs again.

**Comment by JosephMcArthur** [comment]
Can you let us know if the timestamp suggests there is an issue?
