### ISSUE TITLE
Same request listed multiple times

### ISSUE THREAD

**Issue by meganwaps** [OAButton/backend#402]
In making sure we have location on all requests, I noticed that some requests are posted numerous times on the list. 
![screen shot 2016-11-14 at 11 11 10 am](https://cloud.githubusercontent.com/assets/5968703/20280153/214c261a-aa60-11e6-932c-b238eab8c5b7.png)
![screen shot 2016-11-14 at 11 11 00 am](https://cloud.githubusercontent.com/assets/5968703/20280156/26463f84-aa60-11e6-8731-bb9c31e11f66.png)

The dates and locations are the same on each of the duplicate requests, so I'm unable to tell if people are accidentally hitting 'request' multiple times, or if our system is duplicating these requests.

**Comment by markmacgillivray** [comment]
Moving into the current milestone - I will want to get this fixed asap. I would guess it is due to bad connections and so the server receives multiple requests for the same thing before it was possible to save the previous request, so a duplicate becomes possible. We have seen this before, and whilst the new plugin is more stable, there are going to be some occasions due to network issues that we just can't stop. If this is the case, I think the only solution will be that I add a checker for duplicates that dedups them. So will investigate in this sprint and fix if possible.

**Comment by markmacgillivray** [comment]
Noting for myself, I just looked at a live example which has a duplicate, and the difference in creation time is about 5 seconds.

WThs4w9bbmsBSBLpu

**Comment by markmacgillivray** [comment]
Given that the duplicate requests were a few seconds apart, it seemed strange that they could have been created - the system when creating does check for already existing ones, so even if the user was suffering network delay issues or if they pressed the button multiple times (due to delay again perhaps causing it not to disappear immediately, although unlikely) the backend should have refused it.

However, because when creating a request we scrape various bits of metadata out of a page, and this process could take a few seconds, it could be possible that some duplicate requests were coming in before the request had been written to the database.

So I have changed it to save a new request immediately, with just the url and request type, then to do the metadata extraction and to subsequently update the request. This would mean that subsequent duplicate requests for the same URL will not get created.

The only downside is that it is possible that requests will exist which have no metadata at all - however, this should only be the case for a few seconds, and is probably a better downside than that of having duplicates.

I am moving this on to test now, so please just make sure when using the dev site find page that requests still get created as expected, and that they have the expected metadata just as they did before. I have already checked that it works as expected on the API, and did do one on the site too, but still, UI testing is useful to be sure.

**Comment by markmacgillivray** [comment]
Also, once we are happy this is fixed, anyone with admin account can go to the duplicate requests and delete them from the system.

**Comment by JosephMcArthur** [comment]
Okay, I just made a request from /request/new that seemed to have worked just fine. How deep would you suggest we test this @markmacgillivray. From all systems, or is a spot test okay?

**Comment by markmacgillivray** [comment]
@JosephMcArthur I think that will do for now then if we hear from users that they still get this, or if we see more dups on live over the coming weeks, then we can review again.
