### ISSUE TITLE
Library & ILL Bookmarklet Mock up for feedback

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#408]
![bookmarklet ux v1](https://cloud.githubusercontent.com/assets/4953703/20596627/619ea27c-b237-11e6-97c7-e11515c104cd.png)
![imperial page v1](https://cloud.githubusercontent.com/assets/4953703/20596794/0bda86a2-b238-11e6-91f3-ce3ad95b0403.png)

This is the current status of our mockup for a library/ILL version of the tool. Some notes on the status of the design: 
* There are some aesthetic design inaccuracies vs the current tool. Best to pay attention to structure. The intention here was the explore (with the same styling etc) how our current button would need to change to facilitate the. The intention was to keep things as similar as possible

So, to explain some things here:
* A copyright statement has been added as this is currently present on the ILL forms. It was assumed this had to be signed on a case by case basis, so we included it. 
* Data has been removed as it's currently not part of ILL systems. In this case, the focus is on those, so we've removed it here. 
* The orange / green button would respond based on our searches through green sources but also looking through imperials catalogue. 
* If a green source was found, we added the option to do an ILL request. This is due to feedback from the imperial team that their users prefer "final" copies like the ILL system provides. 
* Here ILL & OAB requests are started at once with the same button click. We discussed splitting these at length and giving the user choice but decided this made more sense. 
* "Get it Now" was chosen as the name as the system uses non-oa services. We also expect that we'll have a decreased ability to educate users as to what the service is - so the name needs to be more self-explanatory. This name was lifted from what Imperial calls buttons leading to ILL. It is not intended as a final name, merely an intention to move in a direction that looks more like this.
* Note the removal of our logo, this is intended to be fairly vanilla branding.
* There are two assumed methods of sign up. 1) automatic installation on library PC's. In this case, no real sign up is needed & bookmarklets are generated from Imperial ID's. 2) Sign up via a site. Here, a small landing page has been generated that allows only Imperial addresses. Again, while there are many aesthetic changes here these aren't really intended. 
* It was assumed we'd only do this on the bookmarklet. Plugins can with more install issues for automatic deployment. 

# Questions
* Should we change the tickbox to "by using this service you're agreeing to xyz". So no user action is needed. 
* How can we smoothly handle having this been called something different from the main oab?
* Are there any technical challenges here we haven't anticipated?

**Comment by meganwaps** [comment]
@JosephMcArthur 
- Should we change the tickbox to "by using this service you're agreeing to xyz". So no user action is needed.
If this could be a one-time agreement that would be preferable, based on previous user feedback. 
- How can we smoothly handle having this been called something different from the main oab?
I like maybe oabi, or OAB @Imperial. In using our name it becomes difficult because we might be blamed for technical glitches that are not our fault. Will we be answering questions and issues from these users, or will Imperial? 
- Are there any technical challenges here we haven't anticipated? Kind of what I mentioned above, who is going to handle when things break, who is responsible for what?

**Comment by JosephMcArthur** [comment]
Notes for Joe:
* no sign in on bookmarklets
* if found via library take them straight there
* too complex to see what's going on on the mockup. Does that hold to the tool itself
* analytics
* managing users 
* having libraries being able to see their requests

**Comment by chealsye** [comment]
- Should we change the tickbox to "by using this service you're agreeing to xyz". So no user action is needed**. Yes.** 
- How can we smoothly handle having this been called something different from the main oab? **I think including "Powered by OAB" can help with that. As we discussed in today's meeting, I agree with using subdomains and most of our site still. We can brand it for them, use a generic, catchy name that will make sense to people who aren't familiar with OA.**
- Are there any technical challenges here we haven't anticipated? **I agree with Megan's comments about responsibilities. But otherwise I'm not sure. There might be, but I don't really see the tech side of things. 
-**

**Comment by markmacgillivray** [comment]
Using a bookmarklet for this, and having a unique site for each library, sounds a bit different to what I was expecting here based on previous discussions.

* Get it now / powered by OAB on the bookmarklet itself makes sense

* apart from that, the bookmarklet should remain as close to exactly the same as the normal OAB bookmarklet, and only differ where there is a specific requirement - as far as I can see, that means hiding the open data option, and having a copyright statement checkbox

* having a sign up page that is unique to the library is possible, as long as we know how users will be reaching it. The mockup for that page looks fine, but note it may be a sign UP rather than sign IN the first time round

* but presumably the rest our OAB site remains the same, and we do not need a custom site for Imperial, for each library, right? Just a unique sign in page?

* if we are to identify users by their Imperial IDs only, and not have them sign up to oab at all, we have the same problems as I have described for the journal tool - namely, lack of metadata on our system about the users, and problems for the libraries in being allowed to hand over such metadata about their users to a third party

* How is a library going to install this as a bookmarklet and ensure the user can see it? Are they going to manually manage the bookmarks of their individual user accounts, and the display of those bookmarks in their user browsers? If so, on which browsers? Ideally this should not matter too much, but note for those doing UI testing that it may mean the bookmarklet going on to more browsers than have been checked for so far

* NOTE that using a bookmarklet as an identified user requires DIFFERENT bookmarklet code to be installed for every user. I am not sure how a library are going to manage to automatically install this, for every user on every machine in their estate. This seems different to me to what was originally proposed, for how libraries would

* So it seems either we must expect individual users to install the bookmarklet themselves, or we expect Imperial to do it for them and we pick up their Imperial ID from their login cookie - BUT in this case we will never need to, or be able to, send them to a login page. And we will have the problems mentioned above re. getting metadata about the individual users.

* As with the journal tool and the comments I made there, it seems the mockup itself is OK (although in this case I think could also be kept simply as close to original bookmarklet as possible) but there is more complexity behind the scenes to consider.


In this case I think the recap has to be that we expect to identify users by their Imperial ID, that Imperial therefore have to be able and willing to give us metadata about all of their users (or at least provide us a way to look it up per user - and this may require them asking their users more things about them that they do not already know such as profession), or that we simplify how such requests are logged on our system - e.g. the request came from "an Imperial user" rather than "username who is a profession".

There are further complexities to consider behind the scenes, but as long as we know we can get their Imperial ID from their cookie / login session when they click the bookmarklet, then Imperial could install a generic plugin on all machines - and we accept the above simplified approach to what we know about the user accounts. After that, we then discuss with Imperial how we trigger the ILL request into their system and how they inform our system of progress. I will continue those points in the backend issue.

**Comment by JosephMcArthur** [comment]
Rolling into new mockup now

**Comment by JosephMcArthur** [comment]
* request full article button smaller (in line button)
* GetPDF as name
* Change copyright statement
* No sign in
* service provided by statement
* make mockup easier to understand
* oa to ill request needs clarifying

**Comment by JosephMcArthur** [comment]
<img width="1280" alt="screenshot 2016-12-01 11 12 18" src="https://cloud.githubusercontent.com/assets/4953703/20791998/924e21a6-b7b7-11e6-93e4-27ab23573022.png">

**Comment by JosephMcArthur** [comment]
<img width="1280" alt="screenshot 2016-12-01 11 13 19" src="https://cloud.githubusercontent.com/assets/4953703/20792006/9b10cabe-b7b7-11e6-8b39-da96d1cc4f9f.png">
