### ISSUE TITLE
Journal tool Mock up for feedback

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#409]
![journal button](https://cloud.githubusercontent.com/assets/4953703/20596797/1495de54-b238-11e6-8241-df35688c203d.png)

This is the current status of our mockup for a journal page version of the tool. Some notes on the status of the design: 
* Ignore the tickbox for copyright rules, that was a miscommunication in designing this. 
* We didn't finish the screens for when data is available. The idea would be to display an open data badge, a link to that data & a contact form for the author. The later would be 100% optional but allow you to send your details to an author if you wished to start a collaboration or say why the data was useful. 
* This design also uses the assets we created in previous mockups, so there may be some aesthetic issues vs our current tools. Please ignore these, and try and focus on substantive design issues. 
* The design is missing the email box

The idea here is that journals could install a plugin on their page where people could then use the button without needing to download it first. Some design notes:
* It was assumed that folks would still need to give us some sign up details to use the system. It was also assumed that if people already had the button installed (as bookmarklet or plugin) it would be possible for the button to understand & respond appropriately. If this wasn't the case we'd need to add a "log in" next to the powered by statement. 
* It was assumed the preferred route for journals would for this to have very vanilla branding. Here, we purposefully styled it similar to other buttons on the page. 
* Two basic states are presented to a user, data available or data unavailable. This was chosen as our third state "request made" is likely confusing without context. If a user made a request while one was already in progress then we'd just save that as support. 
* It is assumed we already have the author's email address

## Current Questions
* Should the form all be on one page? I think so 
* Should we reduce the fields required to sign up at this stage? That reduces the info we can use later in the process.
* Strikes me that on a page these fields would be pretty small, should we increase their size? 
* Is the two state simplification a useful / feasible one? 
* We need a statement somewhere along the lines of "Your request will be public as this helps X". What other copy is needed to explain what's happening here? 
* How would this work on mobile (if at all?)

**Comment by markmacgillivray** [comment]
Some quick thoughts:

* we should not have people signing up IN the plugin - if they need an account we should direct them to our signup page then redirect them back to the page they came from, as we already do within our own site.

* So all we need is the embedded button to open the dropdown, which then asks users to sign in or to go to our site to sign up and redirect them back, then they write their story and submit. Alternatively, if users don't have to sign in, the request would need to be created for an account owned by the journal, but the user could still provide their email address to be kept up to date about it (as a supporter of the request created by the journal account).

* if the user already has the plugin installed, the embedded button on the journal does not really have to do anything at all - we could add some code to the plugin to just trigger an opening of the plugin if the user clicks the embedded button but already has the plugin, and not open the embedded dropdown at all - this assumes that journals do not REQUIRE requests created via their site to be created under an account linked to the journal rather than the individual user.

* If the journal website works fine on mobile already, this would work fine on mobile too, as long as the journal people embed it in such a way that it still shows up on the mobile version of their site pages.

* Two state simplification is a good idea to me.

* If we need a "your request will be public" and other caveats, they could just go in the placeholder text in the text box before the user types their story.

* Probably the "powered by open access button" sentence should link to a page on our site that explains OAB in the specific context of the embedded journal tool, then goes on to link out to the rest of our site.

* Is this embedded plugin only going to do data? I don't suppose we can get publishers who DO charge their users to embed it on their page to allow them to find publicly available versions where they already exist... but most publishers do include the links to people to sign in via their institutional connection etc, so it is not like they are totally unhelpful of people getting free (or at least otherwise-paid-for) versions. This is worth considering, perhaps at least asking - maybe some publishers would be OK with this? If we don't consider the possibility at all, then we have to change the embed later to support article requests - and we are already considering other kinds of requests too, so this is something to consider anyway, we may allow people to request things other than data at some point.

**Comment by JosephMcArthur** [comment]
Please note, we're not super close to needing to implement this right now, so I'll probably only take limited feedback. These images only need to be mostly representative for a proposal.

**Comment by JosephMcArthur** [comment]
note to self: this could be used for services like pubmedeu & others who aren't pub's but give articles behind paywalls. Need to expand.

**Comment by meganwaps** [comment]
Since at this stage we need limited feedback, I'm going to answer the questions @JosephMcArthur proposed:

- Should the form all be on one page?  Having done user testing, I can tell you that both long time and new users prefer a streamlined look for the button. They want to open as few windows and as few tabs as possible. So one page would really be paramount. 
- Should we reduce the fields required to sign up at this stage? I'm going to ask another question, at this stage would users already be signed in on their Imperial accounts? What are the logistics behind having them sign up with their Imperial credentials so they are always signed into the button when using this to search for journals. That would be much easier for the user and would encourage them to utilize the button more if they were already signed in.
- Strikes me that on a page these fields would be pretty small, should we increase their size? As long as it doesn't become too 'shouty'. 
- Is the two state simplification a useful / feasible one? @markmacgillivray?
- We need a statement somewhere along the lines of "Your request will be public as this helps X". What other copy is needed to explain what's happening here? What about a video when they first create an account explaining the good a request can do? We've talked about making a short video like this a few times, but I think it could be very useful in this case. 
- How would this work on mobile (if at all?) Can we have access to Imperial's collection so I can see how it looks on mobile? Can Simon release a test username and password for us to utilize?

I'm wondering if it would be acceptable for me to show these mock ups in user tests? I could black out the section saying 'Imperial', but I think if users saw the possibilities it could be positive both in our feedback and in getting people excited about this idea.

**Comment by natalianorori** [comment]
Just gonna go ahead and leave my comments by following Joe's questions:

- Should the form all be on one page? I think this would be the best, less complicated way to go for all of our users. The least tabs the better. 
- Should we reduce the fields required to sign up at this stage? I am not sure about this, This should depend on if the journal already has some info on each of the users. 
- Strikes me that on a page these fields would be pretty small, should we increase their size? Maybe a little, but we should still  try to keep the design simple and clean.
- Is the two state simplification a useful / feasible one? Seems like a good idea. 
- We need a statement somewhere along the lines of "Your request will be public as this helps X". What other copy is needed to explain what's happening here? I agree with Mark with adding this in the text box before the user types their story.

comments: I agree with Mark in making the "powered by the Open Access Button" text redirect to our website.

**Comment by markmacgillivray** [comment]
So it seems we all agree on:

* a simple one-page dropdown
* with no tickbox but implicit agreement on submission
* extra explanatory text in the textarea placeholder text such as "this will be public"
* simplifying / removing signup/signin

I think the biggest point then is signing up /signing in. It simplifies the plugin the most, but is also the most complex to handle. It is not necessarily the technical complexity, but the user workflow, and how the organisations involved want to manage users.

I think all we need for the mockup is that if the user is identified (how they are identified is proposed below), we show the simple dropdown where they read the explanatory placeholder text, write in their own request story, then click the button which has implicit agreement of terms stated below it. But IF the user is not identified, then instead of showing the text box we show a msg saying "this service is provided by oab, you have to sign up / sign in to oab to use it" and instead of the submit button we show a "sign up / sign in" button.

Note, none of what follows matters much for the mockup itself - we just simplify how the tool looks. But we do need to be able to handle the following workflows in some way, behind the scenes. We could just not require sign up on the journal tool. This means we either group all requests from that journal under an account for the journal, OR we identify their users in some way depending on how they manage them. It is possible we could extract user ID from their cookies.

The issues for getting users signed up are:

* for users that already have the plugin, we don't have a problem - they're just using the button, and the journal tool just turns into a useful link that opens the main plugin anyway

* but it is probably not possible to have the bookmarklet interject in this way - there is no way for the journal tool to know the bookmarklet is present, and no way for the bookmarklet to do anything until after it is clicked

* although we may be able to identify a unique user of the journal, we would not know anything about them (nice username, profession, etc). We could ask the journal for this info, but that probably changes their user agreement in ways that are non-trivial for them to solve - and that could differ for every different journal we try to integrate with

* we could ask the users themselves to please provide account info to us to customise their requests. But they may not, so in places where we use info about users to display a request, we would be back to having some using user IDs and nothing else, which looks worse on our site

* if we stick with just putting all those requests under an account for the journal itself, it is less personal and we cannot allow the individual users to sign in and manage those requests (fix their metadata, etc)

* so I think we have to have the journal users sign up to our system too - even if we can identify them via the journal cookies or some other way. Where this is necessary, we should not have users signing up IN the journal tool - for sign up, we redirect the user to our site to sign up, then redirect them back to the page they were on.

* we can ALSO offer automatic sign up for journal users, IF the journal is able to give us a list of users and their details. In this case we just make the accounts ourselves without the users having to do it. But as mentioned above, this is probably not within the rights of what the journals are allowed to do with their user data, and they may not necessarily hold what we need such as profession. But if a journal is willing to get it, we could do this. We could also allow journals to provide some sort of automated informing of user account changes. However, this all involves more work, and should only be done if there is a real use case - e.g. an actual journal wishing to give us data about their users in this way


Now, for signed up users, we still need to know who they are when they perform an action on a journal. Issues with this are:

* if we can identify a user with a journal by reading a journal cookie, or some other in-page value (this is probably possible), all we need is to match a journal user with their OAB account - so when they create their account, I have the journal tool pass some ID from the cookie and we store it. The first time a signed in journal user clicks the journal tool button, we check if they have an account and if not we redirect them to sign up then back to the page

* NOTE though this assumes the journal ONLY shows the journal tool to their signed in users. Is this actually the user story we are building? Are we expecting journals only to offer this to people who are signed in? Aren't they the people most likely to already have access? Would it not be more useful for people who are NOT signed in?

* We can also probably put a cookie into the domain of the journal ourselves, when a user signs up / signs in via our own site. This is likely to be the easiest method, and avoids us having to worry about the journals own auth systems. It still requires that we have users signed up to our service even if they have a journal account though, and it still requires that they actually sign in to our service too, occasionally - except for those cases where specific journals are willing to give us that data about their users on their behalf. However I think this is probably the simplest and best solution.


So to recap, I propose that there is no sign in done on the journal tool itself, that there is no using of journal auth at all, that we do not expect journals to provide us user data (until one comes along who actually says they wish to do so), that on first use we have a journal user sign up to our system too, and that we then authenticate them to our system regardless of whether or not they are signed in with the journal




---------------------------
notes for MM:
* tool embed must receive a response with a token to save in a cookie under the journal domain
* user sign up must record which journal tool triggered it
* user submission must record which journal tool submitted it
* first click must check for url param - if present, POST back to oab to get user creds to set cookie
* on first click if no url param check for cookie - if not present, redirect to oab sign up / sign in
* if a user has an account but is using from a journal tool, save the info of the journal tool they used? really we expect these users just to be using the plugin, but they may be on a different browser / device. Save this info to their user account to show we know they did it, and to allow them a cookie on the journal tool too, and probably also save it on the request itself

**Comment by JosephMcArthur** [comment]
Rolling into new mock up now.

**Comment by JosephMcArthur** [comment]
- [ ] change sign up 
- [ ] powered by is link
- [ ] no sign up required to download
- [ ] can be articles too
- [ ] remove copyright tickbox
- [ ] need statement on request being public in textbox
- [ ] add email box
- [ ] make form one page
