### ISSUE TITLE
Removal of wishlist items?

### ISSUE THREAD

**Issue by mtb-za** [OAButton/backend#48]
I am just wondering if we should consider allowing items to be removed from the wishlist. It is possible that people may get a copy from elsewhere, or they may decide that they do not need it for some reason.

Just opening this for discussion really.

I know that the wishlist features are not finalised yet, but I can see the wishlist getting really long quickly....

**Comment by markmacgillivray** [comment]
This is no longer relevant so closing it. We have block stories just now, then requests for things that people want, but those requests are for everyone who needs something, and being blocked is a support of that request. So a user sees their blocks (although this may change to just being a counter stat for the oab team) and they see their requests, and the status of those requests can be viewed. So a request does not get removed because it can be for more than one person, but it does move through a set of status to indicate how it progressed.
