### ISSUE TITLE
Issue with sidebars on /advocacy

### ISSUE THREAD

**Issue by svmelton** [OAButton/backend#98]
Currently an issue with the sidebars (labeled "Helpful Guides") on the advocacy page: https://openaccessbutton.org/advocacy_staging. The second sidebar doesn't collapse the sections—this is another Javascript issue. The footer is also not displaying correctly.

**Comment by mtb-za** [comment]
Are we expecting a second sidebar there? It looks like it is duplicating the content.

This will cause it to break because it is matching on the first div with the correct ID. If you check, the second sidebar is opening and closing the section above correctly.

Are we planning another load of content here? If not, then the fix is simply to delete it. If we are, then we need to change the ID of the div, and add them to the list at the top of the etherpad.

Just let me know either way.

**Comment by svmelton** [comment]
Thanks for checking! Yeah, we wanted a second sidebar with different content there.

**Comment by mtb-za** [comment]
OK, great. I will get onto it today if the etherpad loads properly.

**Comment by mtb-za** [comment]
I can still not load into the etherpad properly, so I am uploading new pages to a new branch, which will hopefully be able to replace the current content correctly. Just copy them into the etherpad.

**Comment by mtb-za** [comment]
This has been fixed.

Closing for now. It might still need new copy.
